### ISSUE TITLE
Unable to run count-kmer-abundances.pl 

### ISSUE THREAD

**Issue by gkarthik** [jenniferlu717/Bracken#1]
The following command doesn't seem to work despite modifying how I supply the arguments,

`perl count-kmer-abundances.pl --db=/home/db/kraken/kraken_full/ --read-length=150 TEMP192.kraken.full.output`

Output:
```

USAGE: count-kmer-abundances.pl
 <read size> database.kraken
```

TEMP192.kraken.full.output is the kraken output for a fastq file.

**Comment by jenniferlu717** [comment]
Did you download the newest version of count-kmer-abundances? We updated it today.

**Comment by jenniferlu717** [comment]
Also, you probably want to pipe the output into another file:

`perl count-kmer-abundances.pl --db=/home/db/kraken/kraken_full/ --read-length=150 TEMP192.kraken.full.output > TEMP192.kraken150mers.kraken`
