### ISSUE TITLE
Read_length

### ISSUE THREAD

**Issue by skerker** [jenniferlu717/Bracken#10]
Hi,

I used PE150 data for classification.  Should I use a read length of 150 or 300 for the read_length parameter in your count-kmer-abundances.pl script?  My understanding is that PE data gets concatenated into 150 - N - 150, so would that be a length of 300?

Thank you!
Jeff

**Comment by jenniferlu717** [comment]
I would use 150. When we tested our paired end reads, we tried both 150 and 300 and discovered more accuracy with 150.
