### ISSUE TITLE
Total number of reads is inflated, up to a factor 2

### ISSUE THREAD

**Issue by Wrzlprmft** [jenniferlu717/Bracken#102]
Bracken inflates the total number of read counts, up to a factor 2. I observed this with a database, where the factor strongly depended on the taxonomic level to which I applied Bracken, with the factor approaching 2 for higher taxonomic levels.

### Minimal example:

I obtained the Bracken database as well as the Kraken 2 report in this example by applying a minimal Kraken 2 database to a subset of a real dataset.

Create a folder containing the following files:

* 	`report.dat`:
	```
	  7.20	17614	17614	U	0	unclassified
	 92.80	227065	0	R	1	root
	 92.80	227065	0	R1	131567	  cellular organisms
	 92.80	227065	0	D	2	    Bacteria
	 92.80	227065	0	P	1224	      Proteobacteria
	 88.42	216335	0	C	1236	        Gammaproteobacteria
	 88.42	216335	0	O	72274	          Pseudomonadales
	 88.42	216335	0	F	135621	            Pseudomonadaceae
	 88.42	216335	0	G	286	              Pseudomonas
	 88.42	216335	0	G1	136841	                Pseudomonas aeruginosa group
	 88.42	216335	0	S	287	                  Pseudomonas aeruginosa
	 88.42	216335	216335	S1	208964	                    Pseudomonas aeruginosa PAO1
	  4.39	10730	0	C	28211	        Alphaproteobacteria
	  4.39	10730	0	O	204458	          Caulobacterales
	  4.39	10730	0	F	76892	            Caulobacteraceae
	  4.39	10730	0	G	41275	              Brevundimonas
	  4.39	10730	10730	S	293	                Brevundimonas diminuta
	```

* 	`mini_db/database151mers.kmer_distrib`:
	```
	mapped_taxid	genome_taxids:kmers_mapped:total_genome_kmers
	0	208964:1876:6264254 293:6068:3551669 
	208964	208964:6262378:6264254 
	293	293:3545601:3551669 
	```

Then run:
```
bracken -d mini_db -i report.dat -r 151 -o /dev/null -w bracken_report.dat
```

This returns the following report for me:
```
200.00	454130	0	R	1	root
200.00	454130	0	R1	131567	  cellular organisms
200.00	454130	0	D	2	    Bacteria
200.00	454130	0	P	1224	      Proteobacteria
190.55	432670	0	C	1236	        Gammaproteobacteria
190.55	432670	0	O	72274	          Pseudomonadales
190.55	432670	0	F	135621	            Pseudomonadaceae
190.55	432670	0	G	286	              Pseudomonas
190.55	432670	0	G1	136841	                Pseudomonas aeruginosa group
190.55	432670	432670	S	287	                  Pseudomonas aeruginosa
9.45	21460	0	C	28211	        Alphaproteobacteria
9.45	21460	0	O	204458	          Caulobacterales
9.45	21460	0	F	76892	            Caulobacteraceae
9.45	21460	0	G	41275	              Brevundimonas
9.45	21460	21460	S	293	                Brevundimonas diminuta
```

**Comment by jenniferlu717** [comment]
I had made some changes to the Bracken script over the past couple of weeks. Can you confirm this is with the newest Bracken script?

**Comment by Wrzlprmft** [comment]
Yes, it is. I haven’t tried other versions.

**Comment by jenniferlu717** [comment]
Oh I know what happened. I fixed the Bracken output but I didn't fix the Bracken report. Give me a few minutes and i'll have it fixed. Apologies, and thanks for noticing the error.

**Comment by jenniferlu717** [comment]
I made a change, can you check to see if the problem is fixed? 

Thank you

**Comment by Wrzlprmft** [comment]
The minimal example seems fine now. The results for actual data I am working with are clearly better, but I still get weird results for levels that are not well represented, namely:

* When choosing `K` (kingdom) as a level for a bacteria-dominated dataset, the respective report completely discards all bacteria.
* When choosing `S1` as a level, a genus with a detailed subspecies structure in my database gets inflated, in one case from 94% for `S` to 98% for `S1`.

In general, I would strongly recommend to have some automated tests to avoid such issues in the future.
