### ISSUE TITLE
kraken2-build not using available threads 

### ISSUE THREAD

**Issue by pietermonsieurs** [jenniferlu717/Bracken#104]
When running the following command: kraken2-build --standard --threads 20 --db ~/scratch/data/kraken/, I noticed that the process is only using one single CPU, and not all available 20 cores. I would assume that e.g. when running the dustmasker, all CPUs would be occupied. 
Any idea on how I can solve this?

**Comment by Wrzlprmft** [comment]
Unless I completely misunderstand something, this appears to be a problem with Kraken and not with Bracken and thus belongs [here](https://github.com/DerrickWood/kraken2/issues).

**Comment by pietermonsieurs** [comment]
Indeed, apologies! I will post it on the Kraken github
