### ISSUE TITLE
kmer_distrib not found, but actually exists

### ISSUE THREAD

**Issue by MatteoSchiavinato** [jenniferlu717/Bracken#109]
Hi, 
I'm attempting to use Bracken in my workflow, but I am having the weirdest of errors.

Here is what it says:
```
[schmat@l31 results]$ cat F35_D_R4.bracken.stderr
 >> Checking for Valid Options...
 ERROR: /binfl/lv70694/schmat/chicken/kraken2/maxikraken2_1903_140GB/database100mers.kmer_distrib does not exist
        Run bracken-build to generate the kmer distribution file.
```

And here is the file: 
```
[schmat@l31 results]$ ll /binfl/lv70694/schmat/chicken/kraken2/maxikraken2_1903_140GB/database100mers.kmer_distrib
-rw-r--r-- 1 schmat p70694 348 Aug  4 19:26 /binfl/lv70694/schmat/chicken/kraken2/maxikraken2_1903_140GB/database100mers.kmer_distrib
```

Is there any reason, why bracken may not see this file?

**Comment by jenniferlu717** [comment]
Hm strange. What is the command line you gave?

**Comment by MatteoSchiavinato** [comment]
I'm using it in a slurm system, with the following command nested in a sbatch file:

```
{ \
/binfl/lv70694/schmat/chicken/bracken/bracken_programdir/bracken \
-d /binfl/lv70694/schmat/chicken/kraken2/maxikraken2_1903_140GB \
-i /binfl/lv70694/schmat/chicken/kraken2/results/F3_F_R1.report \
-o F3_F_R1.bracken \
-w F3_F_R1.bracken.report \
-r 100 \
-l G \
-t 0 \
; } \
&> F3_F_R1.bracken.stderr
```

I added the `\` to simplify reading of the command.

**Comment by jenniferlu717** [comment]
Can you try using the python command instead?

python estimate_abundance.py -i ${SAMPLE}.kreport -k database${READ_LEN}mers.kmer_distrib -l ${CLASSIFICATION_LVL} -t ${THRESHOLD} -o ${BRACKEN_OUTPUT_FILE}.bracken 

I'm not sure why its not working honestly. I haven't come across that error but I also have never run Bracken in a slurm system.

**Comment by MatteoSchiavinato** [comment]
```
python src/est_abundance.py -i /binfl/lv70694/schmat/chicken/kraken2/results/F3_F_R1.report -o F3_F_R1.bracken -k /binfl/lv70694/schmat/chicken/kraken2/KRAKEN_DB/database50mers.kmer_distrib -l G -t 0
```

I get: 
```
PROGRAM START TIME: 08-13-2020 10:44:33
Traceback (most recent call last):
  File "/binfl/lv70694/schmat/chicken/bracken/bracken_programdir/src/est_abundance.py", line 501, in <module>
    main()
  File "/binfl/lv70694/schmat/chicken/bracken/bracken_programdir/src/est_abundance.py", line 222, in main
    report_vals = process_kraken_report(line)
  File "/binfl/lv70694/schmat/chicken/bracken/bracken_programdir/src/est_abundance.py", line 140, in process_kraken_report
    level_reads = int(split_str[2])
IndexError: list index out of range
```

**Comment by MatteoSchiavinato** [comment]
I edited your est_abundance.py script with a print statement here and there, to see which lines were throwing out errors. It is the very first line of the input file: 

```
d__Bacteria	8559261
```

Because it tries to split this into a list of at least 4-5 elements. However, in the Kraken REPORT file (as the bracken help says to use for `-i`) this is usually the first line. 

Am I missing something?

**Comment by MatteoSchiavinato** [comment]
I was indeed missing something. It seems that I generated the report with Kraken2 using `--use-mpa-style` while that is not the right option if Bracken has to be used later. 

Maybe it's just me, but it would be helpful if this was specified somehow in the bracken help section (even just something like "not mpa"). I guess this can be closed.

**Comment by jenniferlu717** [comment]
Ah sorry. I keep meaning to put in error catches in the code to help fix these problems but I haven't quite gotten around to it.

I'll add it to the help section. Thanks for debugging with me.
