### ISSUE TITLE
Which column to use to build abundance profile

### ISSUE THREAD

**Issue by punnettsun** [jenniferlu717/Bracken#112]
Hi,

I looked at the different columns for the Bracken output. I have not actually ran Bracken before, so I do not know what each of the columns look like in the Bracken output file. Which column do I use if I want to visualize the abundance at the genus level? Would it be the "Total Reads after Abundance Reestimation" column or the "Fraction of Total Reads" column? 

Thank you.

**Comment by jenniferlu717** [comment]
"Total Reads after Abundance Reestimation" is the best column for abundance estimation.

**Comment by punnettsun** [comment]
Thank you!
