### ISSUE TITLE
Clarification on Abundance

### ISSUE THREAD

**Issue by punnettsun** [jenniferlu717/Bracken#114]
Hello,

I am slightly confused about how the relative abundance estimates work. From my understanding, if I want to get genus-level abundance estimates, then I'm assuming that reads classified at the species-level by Kraken 2 get aggregated up to the genus-level? What happens to reads if I wanted species-level abundance estimates? Would the higher taxonomic rank reads get aggregated down to species level or does this not work? Please correct my understanding.

Thank you.

**Comment by jenniferlu717** [comment]
For Genus level abundance estimates, reads above will get pushed to genus level and species get aggregated up to genus.

For Species level abundance estimates, reads above will get pushed to the species level .

**Comment by punnettsun** [comment]
I tried to understand the Bracken paper but had been slightly confused if I was thinking about it correctly. Thank you for the clarification and for the quick response!
