### ISSUE TITLE
Hard Version: Step 3 Problem: AttributeError: 'NoneType' object has no attribute 'level_num'

### ISSUE THREAD

**Issue by punnettsun** [jenniferlu717/Bracken#121]
Hi,

I just started to Bracken2 and every step was going well until Step 3 where I got the AttributeError. I was able to get all of the files needed for each step. I have attached the error prompt in the text file below. Please let me know why I am seeing this error.

[bracken2_error_message.txt](https://github.com/jenniferlu717/Bracken/files/5321147/bracken2_error_message.txt)
Thank you.

**Comment by jenniferlu717** [comment]
I'll need the report file as well to determine why the error is being caused.

**Comment by punnettsun** [comment]
Hi Jennifer,

I just re-ran everything again and this is the error message as well as the report file. I'm attaching it here as a .txt file since I can't seem to get GitHub to load the .kreport extension.

<img width="568" alt="Bracken_error_message" src="https://user-images.githubusercontent.com/30707159/97112964-82cf3f80-16a4-11eb-9830-a5b5721ef29a.png">

[test_5.kreport.txt](https://github.com/jenniferlu717/Bracken/files/5435301/test_5.kreport.txt)

**Comment by punnettsun** [comment]
Hi Jennifer,

Bracken is working perfectly now! It seems that my nodes & names.dmp files did not have a column included. This column is the one where it has just a "-" for each of the rows. I was able to add this in and now, there are no errors when I run Kraken2 and Bracken2 together. 

Thank you.
