### ISSUE TITLE
Segmentation fault for the kmer2read_distr  step

### ISSUE THREAD

**Issue by biofuture** [jenniferlu717/Bracken#123]
./Bracken-master/src/kmer2read_distr --seqid2taxid GTDB_Kraken2/seqid2taxid.map --taxonomy GTDB_Kraken2/taxonomy/ --kraken GTDB_Kraken2/database.kraken --output GTDB_Kraken2/database150mers.kraken -k 35 -l 150  -t 20
	>>STEP 0: PARSING COMMAND LINE ARGUMENTS
		Taxonomy nodes file: GTDB_Kraken2/taxonomy/nodes.dmp
		Seqid file:          GTDB_Kraken2/seqid2taxid.map
		Num Threads:         20
		Kmer Length:         35
		Read Length:         150
	>>STEP 1: READING SEQID2TAXID MAP
		3199690 total sequences read
	>>STEP 2: READING NODES.DMP FILE
		45502 total nodes read
Segmentation fault

**Comment by Midnighter** [comment]
I also get a segmentation fault but in a later step in a conda Python 3.8 environment with

```
  - bracken=2.6.0=py38hed8969a_2
  - kraken2=2.0.9beta=pl526hc9558a2_0
```

last output:

```
 >> Selected Options:
       kmer length = 35
       read length = 100
       database    = DB
       threads     = 20
 >> Checking for Valid Options...
 >> Creating database.kraken [if not found]
          database.kraken exists, skipping creation....
          Finished creating database.kraken [in DB folder]
 >> Creating database100mers.kmer_distrib 
        >>STEP 0: PARSING COMMAND LINE ARGUMENTS
                Taxonomy nodes file: DB/taxonomy/nodes.dmp
                Seqid file:          DB/seqid2taxid.map
                Num Threads:         20
                Kmer Length:         35
                Read Length:         100
        >>STEP 1: READING SEQID2TAXID MAP
                6878655 total sequences read
        >>STEP 2: READING NODES.DMP FILE
                2281052 total nodes read
        >>STEP 3: CONVERTING KMER MAPPINGS INTO READ CLASSIFICATIONS:
                100mers, with a database built using 35mers
                6863469 sequences converted (finished: 58395_seq3|kraken:taxid|1673721)~/miniconda3/envs/bracken/bin/bracken-build: line 166: 560962 Segmentation fault     
 (core dumped) kmer2read_distr --seqid2taxid $DATABASE/seqid2taxid.map --taxonomy $DATABASE/taxonomy/ --kraken $DATABASE/database.kraken --output $DATABASE/database${READ_LEN}mers.kraken -k 
${KMER_LEN} -l ${READ_LEN} -t ${THREADS}
```

I can see the following files in the database directory:

```
-rw-r--r-- 1 moritz moritz 538M Oct 14 06:32 database100mers.kraken
-rw-r--r-- 1 moritz moritz  23G Oct 14 06:17 database.kraken
-rw-r--r-- 1 moritz moritz  30G Oct 14 06:02 hash.k2d
drwxr-xr-x 6 moritz moritz 4.0K Oct 14 01:58 library
-rw-r--r-- 1 moritz moritz   56 Oct 14 06:02 opts.k2d
-rw-r--r-- 1 moritz moritz 296M Oct 14 05:18 seqid2taxid.map
-rw-r--r-- 1 moritz moritz 1.6M Oct 14 05:29 taxo.k2d
drwxr-xr-x 2 moritz moritz 4.0K Oct 14 05:18 taxonomy
```

**Comment by Midnighter** [comment]
For me the segmentation fault was due to lack of memory. Would be handy to catch allocation errors and provide a clear error message that the program is out of memory.

**Comment by biofuture** [comment]
Hi, the error is in this block of code


   /*Traverse through parent array and make sure all parents/children are linked*/
    map<int, taxonomy *> children;
    taxonomy * parent;
    for (auto const& pair : parent2kids) {
        curr_parent = pair.first;
        parent = taxid2node[curr_parent];
        children = pair.second;
        for(auto const& child : children) {
            curr_taxid = child.first;
                printf("  hereh \n");
                if(curr_taxid != 1){
                        **taxid2node[curr_taxid]->add_parent(parent);**
                }
            parent->add_child(taxid2node[curr_taxid]);
        }
    }

I do not know why the code report segment default here taxid2node[curr_taxid]->add_parent(parent);

**Comment by biofuture** [comment]
I finally find the reasons why . 

in the node.dump file, for the root node 1, it does not have a parent node. 

        if(curr_taxid != 2 && curr_taxid != 2766){
                parent->add_child(taxid2node[curr_taxid]);
        }
