### ISSUE TITLE
Error generating kmer distribution file

### ISSUE THREAD

**Issue by rachaellappan** [jenniferlu717/Bracken#13]
Hi Jennifer,

I am having trouble with `generate_kmer_distribution.py`. I am running:

```bash
generate_kmer_distribution.py -i /REFERENCE/genomes/rlappan/krakendb_75mers_bracken -o /REFERENCE/genomes/rlappan/bracken_kmer_distribution.txt
```

where the `krakendb_75mers_bracken` file was output from `count_kmer_abundances.pl`.

The error I get is:

```bash
Traceback (most recent call last):
  File "/home/san/rlappan/bin/Bracken-master/generate_kmer_distribution.py", line 161, in <module>
    main()
  File "/home/san/rlappan/bin/Bracken-master/generate_kmer_distribution.py", line 112, in main
    [genome_taxid, total_kmers, mapped_taxids_kmers] = parse_single_genome(line)
  File "/home/san/rlappan/bin/Bracken-master/generate_kmer_distribution.py", line 79, in parse_single_genome
    total_kmers += int(curr_kmers)
ValueError: invalid literal for int() with base 10: 'taxid|170325'
```

When I look at the kmer count file, it looks like this (there are no headers):

```bash
NC_006389.1|kraken:taxid|272569 272569  272569  33303   272569:32874 2237:138
NC_006390.1|kraken:taxid|272569 272569  272569  33452   272569:33292
NC_006391.1|kraken:taxid|272569 272569  272569  39521   272569:39331 1963268:42
NC_001869.1|kraken:taxid|64091  64091   64091   191346  2242:173183 183963:7205 64091:7056 2239:3018 2235:468 2157:141
NC_006397.1|kraken:taxid|272569 272569  272569  288050  272569:268570 2237:18180 1963268:351 183963:278 2235:62 2157:10 28890:2
NC_002608.1|kraken:taxid|64091  64091   64091   365425  2242:337210 183963:13361 64091:7972 2239:4888 2235:958 2157:608
NC_005877.1|kraken:taxid|263820 263820  263820  1545895 263820:1436272 2301:204
```

This seems to match the description of the file format from your manual here:
- Identification string for the read
- NCBI Taxonomy ID of the genoome being classified
- NCBI Taxonomy ID of the classification Kraken assigned to the full read
- Sequence length of the read
- NCBI Taxonomy ID of the classification Kraken assigned to each kmer within the read

but I notice that the sample file you provide looks different:

```bash
mapped_taxid    genome_taxids:kmers_mapped:total_genome_kmers
477974  477974:2348914:2349403
1718    196627:1285495:3309328 340322:1283860:3363153
211586  211586:4973790:5131278
272943  272943:2996513:4602466
272944  272944:606556:1268682
272947  272947:1075421:1111450
347834  347834:6501089:6529717
411154  411154:3797700:3798392
370552  370552:264883:1928179
```

**Should I remove the `NC_00XXXX.1|kraken:taxid|` part from each line of my file?**

As the `generate_kmer_distribution.py` and `est_abundance.py` steps don't actually refer to the original Kraken database again, can I assume that doing so won't cause problems down the line?

Thank you for creating Bracken!

Regards,
Rachael

**Comment by jenniferlu717** [comment]
The sample file provided is the output of the `generate_kmer_distribution.py` program so I'm unsure about what the issue is. I double-checked and the format of your kmer count file looks correct but I'm unsure about why the code is behaving in that way.

Can you email me the krakendb_75mers_bracken file so I can check? jlu26@jhmi.edu.

**Comment by rachaellappan** [comment]
Right, my mistake. Thank you - I will email you the file.

An additional question: I have left the read length for `count_kmer_abundances.pl` at default (75) because I wasn't sure what it should be. Is this supposed to match the read length of my sequencing data? Would it matter if I have trimmed poor quality bases beforehand and not all reads are of that length?

**Comment by jenniferlu717** [comment]
During testing, we found that longer read lengths for that script (around the read length of the sequencing data) would be most accurate, so as long as your reads are 75+bp long, I would assume that it would be fine. It doesn't need to be exactly that length though.

**Comment by rachaellappan** [comment]
Thanks. I am using KneadData so anything shorter than 70% of initial read length after trimming gets discarded; I have 125bp paired end reads, so would 85mers perhaps be more accurate? I note that in another issue you say that using the single-end read length instead of the full merged length was more accurate (I don't merge the reads).

**Comment by jenniferlu717** [comment]
For your initial error, it looks like you concatenated two files to make the krakendb_75mers_bracken file. For some reason, line 7439 has two reads represented. There needs to be an "\n" endline before NC_030117.1 and then the `generate_kmer_distribution.py` program should run correctly. 

I think 75mers would work fine if you don't want to regenerate the file but yes, in that case, 85mers would be the most accurate.

**Comment by rachaellappan** [comment]
Thank you for working this out so quickly! I'm not certain why I ended up with two reads on the same line in that file, as I have concatenated Kraken report files together but they haven't been used in any of these scripts yet. I did Step 2a and 2b following the Bracken manual to obtain the 75mers file:

```bash
# Step 2a
kraken --db /REFERENCE/genomes/rlappan/downloads/kraken_db_100417 --fasta-input --threads=10 --gzip-compressed <( find -L /REFERENCE/genomes/rlappan/downloads/kraken_db_100417/library/added -name "*.fna.gz" -exec cat {} + ) > /REFERENCE/genomes/rlappan/krakendb_for_bracken 

# Step 2b
perl count-kmer-abundances.pl --db /REFERENCE/genomes/rlappan/downloads/kraken_db_100417 --threads 10 /REFERENCE/genomes/rlappan/krakendb_for_bracken > /REFERENCE/genomes/rlappan/krakendb_75mers_bracken
```

so I'm not too sure how that happened - any ideas? This actually happened twice in the file (lines 7439 and 9207), so I inserted newlines where appropriate and ran `generate_kmer_distribution.py` which now runs successfully.

**Comment by jenniferlu717** [comment]
I'm not sure as I haven't come across this error before. I'll double-check the scripts but it looks like those commands are correct.

**Comment by rachaellappan** [comment]
No worries. When I ran `count-kmer-abundances.pl` it printed (around 75% of the way through) that there was one taxon it couldn't find in `nodes.dmp` so I thought that might have caused it to forget the newline, but the same happened when I repeated this step for 85mers and the resulting file had no problems.
