### ISSUE TITLE
No reads kept at domain level

### ISSUE THREAD

**Issue by catarinaloureiro** [jenniferlu717/Bracken#131]
Hi!

I am trying to run bracken on kraken2 results.

It all seems to do fine at phylum and genus level,

for example at phylum:
    >>> Threshold: 1 
    >>> Number of phylums in sample: 151 
          >> Number of phylums with reads > threshold: 151 
          >> Number of phylums with reads < threshold: 0 
    >>> Total reads in sample: 40665805
          >> Total reads kept at phylums level (reads > threshold): 9766183
          >> Total reads discarded (phylums reads < threshold): 0
          >> Reads distributed: 0
          >> Reads not distributed (eg. no phylums above threshold): 1427633
          >> Unclassified reads: 29471989

however when I try to get a domain overview:
    >>> Threshold: 1 
    >>> Number of domains in sample: 0 
	  >> Number of domains with reads > threshold: 0 
	  >> Number of domains with reads < threshold: 0 
    >>> Total reads in sample: 40665805
	  >> Total reads kept at domains level (reads > threshold): 0
	  >> Total reads discarded (domains reads < threshold): 0
	  >> Reads distributed: 0
	  >> Reads not distributed (eg. no domains above threshold): 11193816
	  >> Unclassified reads: 29471989

How come that it is not picking up reads at domain level? 
Thanks!!

**Comment by jenniferlu717** [comment]
What command line are you using for domain level? Can you show the first few lines of your Kraken report?

**Comment by catarinaloureiro** [comment]
bracken -d /databases/kraken/bracken -i krakenreport.tsv -o kraken_bracken1_domain.report -r 150 -l D -t 1

 72.47  29471989        29471989        U       0       unclassified
 27.53  11193816        52686   R       1       root
 26.97  10969027        1373519 R1      3         Bacteria
  8.36  3400164 181564  P       110         Proteobacteria
  4.41  1793246 155939  C       175           Alphaproteobacteria
  1.39  563940  37092   O       1021            Rhizobiales
  0.53  215950  21787   F       2733              Rhizobiaceae
  0.09  35768   7719    G       8700                Rhizobium
  0.00  882     882     S       28654                 Rhizobium altiplani
  0.00  800     800     S       28731                 Rhizobium sp900469615
  0.00  692     692     S       28686                 Rhizobium phaseoli
  0.00  644     644     S       28720                 Rhizobium sp900465675

**Comment by jenniferlu717** [comment]
Oh interesting. It looks like Bacteria (and other domains) were assigned level R1 instead of D. Can you try running Bracken with R1 instead?

**Comment by catarinaloureiro** [comment]
you mean R1 at the -l option? I'll do so and post back the result :)

**Comment by catarinaloureiro** [comment]
yep that fixed it! Thanks! curious though any idea why this happened, and would it mean the other taxa levels are skewed too?

    >>> Threshold: 1 
    >>> Number of R1 in sample: 2 
	  >> Number of R1 with reads > threshold: 2 
	  >> Number of R1 with reads < threshold: 0 
    >>> Total reads in sample: 40665805
	  >> Total reads kept at R1 level (reads > threshold): 11141130
	  >> Total reads discarded (R1 reads < threshold): 0
	  >> Reads distributed: 0
	  >> Reads not distributed (eg. no R1 above threshold): 52686
	  >> Unclassified reads: 29471989

**Comment by jenniferlu717** [comment]
No other levels should be fine. Its just a weird thing depending on which database that domains are either D or R1....we havent made it consistent so apologies for that
