### ISSUE TITLE
Bracken vs kraken2 abundance differences

### ISSUE THREAD

**Issue by jsgounot** [jenniferlu717/Bracken#139]
Hi,

I'm new with both kraken and bracken analyses.
I found out that kraken2 already output abundance in its report file.
When I ran bracken on this report file, I got new abundance values but since bracken ignore unclassified reads, I wonder if the differences I observe between the two report files results from bracken ignoring unclassified or if it's from something else.

Edit : After investigation, I realized that the point of running bracken is also to add some reads using the bayesian analysis, which I guess impact the outcome. Sorry for the inconvenience ! 

Thanks for your time,
jsgounot

**Comment by jenniferlu717** [comment]
No worries at all! I understand the confusion. I'm going to close this issue but feel free to open another issue if you have any questions/concerns.
