### ISSUE TITLE
Maintenance of Kraken?

### ISSUE THREAD

**Issue by andzandz11** [jenniferlu717/Bracken#15]
Will you guys take over the maintenance of kraken? The developer left academics and there are issues at the moment. Genbank is no longer using gi numbers, for example. In the future similar problems might occur. Who will take care of that?
I am starting a 3-yr project and I hesitate to use kraken, because it is unsure whether bugs will be fixed in a timely manner.

**Comment by jenniferlu717** [comment]
We are in the process of transitioning the upkeep of Kraken and addressing those issues. We still use Kraken in our projects so we are aware of the current issues (especially with regards to the gi numbers) and we do hope to release some fixes/updates to address them soon.

**Comment by jenniferlu717** [comment]
We have updated Kraken to no longer require gi numbers. Derrick, myself, and Florian Breitwieser will be maintaining and updating the software over the next year.
