### ISSUE TITLE
Bracken and metatranscriptome data

### ISSUE THREAD

**Issue by klbeck** [jenniferlu717/Bracken#16]
Do you know of anyone with experience running Bracken with metatranscriptome data? It seems appealing to be able to recover some of the reads assigned at a higher taxonomic level, but I don't know if there are huge limitations to why this shouldn't be applied with metatranscriptome data that I'm not aware of yet.

Thank you in advance for your help. I've also posted this on BioStars if you would like to contribute an answer there instead https://www.biostars.org/p/273577/

**Comment by jenniferlu717** [comment]
Hello,

I do not know of anyone running Bracken with metatranscriptome data unfortunately. You could check with the Kraken google community to see if anyone has.

-Jennifer Lu

**Comment by klbeck** [comment]
Good suggestion. Thank you.
