### ISSUE TITLE
No classified, neither unclassified sequences in paired fastq sequences

### ISSUE THREAD

**Issue by MGorostidi** [jenniferlu717/Bracken#166]
Hey you all!

I'm trying to characterized some sequences of a RNAseq pool with the aim of seeing if there is any bacteria, fungi or plant in them. I'm running the following command and, even if I have tried different parameters for Kraken2, I'm constantly obtaining the result of 0 classified and 0 unclassified sequences. Could it be an error I have done? Or should I assume that there is no any of these species in my sample?

*They are supposed to be non-human sequences, since the 2 fastq files are the unmapped result from STAR algorithm and have already been mapped against the Human Genome.

`$ time perl kraken2 --db DB30August --threads 4 --paired --classified-out cseqs#.fq --unclassified-out uncseqs#.fq ./Sequences/Pool1.out.mate1.fastq ./Sequences/Pool1.out.mate2.fastq`

Loading database information... done.
0 sequences (0.00 Mbp) processed in 0.001s (0.0 Kseq/m, 0.00 Mbp/m).
  0 sequences classified (-nan%)
  0 sequences unclassified (-nan%)

real	7m55,107s
user	0m0,168s
sys	1m41,420s

The steps I have followed are: 
1. Download taxonomy: 
perl kraken2-build --download-taxonomy --db DB30August

2. Download libraries:
perl kraken2-build --download-library bacteria --db DB30August
perl kraken2-build --download-library fungi --db DB30August
perl kraken2-build --download-library plant --db DB30August

3. Build Database: 
perl kraken2-build --build --db DB30August 
*This took around 7 hours

4. Classification:
time perl kraken2 --db DB30August --threads 4 --paired --classified-out cseqs#.fq --unclassified-out uncseqs#.fq ./Sequences/Pool1.out.mate1.fastq ./Sequences/Pool1.out.mate2.fastq`

Thank you in advanced for your help :)

**Comment by laibinhuang** [comment]
I am using Kraken2 for classification, but I get some errors: would you mind helping me out. Thank you very much.
The code:KRAKEN_DB="/home/lbhuang/ref/kraken/ABFPV/" 
#note ABFPV is a database built using kraken2 just has three files after clean step:hash.k2d: Contains the minimizer to taxon mappingsopts.k2d: Contains information about the options used to build the databasetaxo.k2d: Contains taxonomy information used to build the databasecd /home/lbhuang/Moore/results/trimmed/
for i in *_R1_trimmed.fastq.gz
do
        filename=$(basename "$i") #do not add \ after this#
        fname="${filename%_R1_trimmed.fastq.gz}" #do not add \ after this#
        kraken2 --db ${KRAKEN_DB}  \
        --confidence 0.01 \
        --threads 32 \
        --use-names \
        --use-mpa-style \
        --output /home/lbhuang/Moore/results/K2/k2_outputs/${fname}_output.txt \
        --report /home/lbhuang/Moore/results/K2/k2_reports/${fname}_report.txt \
        --paired $fname_R1_trimmed.fastq.gz  $fname_R2_trimmed.fastq.gz 
done
