### ISSUE TITLE
Is dual-output (both mpa+kraken styles) possible on a single run? 

### ISSUE THREAD

**Issue by jorondo1** [jenniferlu717/Bracken#181]
I would like to use the Kraken2 output as (1) input to Bracken and (2) input to HUMAnN3 functional profiling (substituting for the MetaPhlAn3 output, which is less suited to our data's characteristics.

Is that something that can be done ? If not directly, is there an intermediate computing step or a temp file from which output generation could be rerun to get the mpa style after a standard run?

**Comment by jenniferlu717** [comment]
I believe these programs should help: https://github.com/jenniferlu717/KrakenTools

**Comment by jorondo1** [comment]
They did! Sorry for not closing this earlier, those were my first steps in metagenomics. KrakenTools is awesome. Thanks for replying !
