### ISSUE TITLE
Documentation improvement on additional scripts paths'

### ISSUE THREAD

**Issue by asan-emirsaleh** [jenniferlu717/Bracken#188]
Hello!
Thank your for really great and useful tool. It has been made with a lot of detail in mind.
I have discovered `estimate_abundance.py` not to be working in conda distribution of Bracken. The `est_abundance.py` worked in my case. Also you have this script in `https://github.com/jenniferlu717/Bracken/blob/master/src/est_abundance.py` path of your github page. 
So you can change the Readme for paths' to resolve.

Thank you again.

**Comment by jenniferlu717** [comment]
I do not maintain the conda version of Bracken so I do not know how to help with that

**Comment by asan-emirsaleh** [comment]
Sorry, you have the same problem at the Readme.

**Comment by asan-emirsaleh** [comment]
Would you introduce any changes into your code or docs? I noticed you have incongruency there. Please look at the commit to make Readme and real script names consistent.

Best regards
Asan
