### ISSUE TITLE
Dependencies of bracken

### ISSUE THREAD

**Issue by crarlus** [jenniferlu717/Bracken#19]
Could you extend the readme with a section "installation" that includes the perl and python modules required for running BRACKEN?

For best usability, you could provide BRACKEN as a [bioconda](https://bioconda.github.io/index.html) package.

Thank you!

**Comment by jenniferlu717** [comment]
I'll update the README ASAP (hopefully within the next two days)

**Comment by druvus** [comment]
@crarlus @jenniferlu717 The latest release of Bracken (v1.0.0) is available as a bioconda package. I am happy to assist to update it once it is a new release.

**Comment by jenniferlu717** [comment]
That is absolutely amazing to hear @druvus. Thank You!

**Comment by druvus** [comment]
@jenniferlu717 I will fix it during the week. Just realised that kraken/kraken2 were not yet rebuilt with conda3 and perl 5.26 so I need to fix that first.

**Comment by druvus** [comment]
@jenniferlu717 Bracken 2.2 was added to Bioconda by @dfornika in PR  bioconda/bioconda-recipes#11094. Unfortunately we still not have rebuilt osx versions of kraken/kraken2
