### ISSUE TITLE
Unique reads is 0 or all ?

### ISSUE THREAD

**Issue by TheSallyGardens** [jenniferlu717/Bracken#192]
@jenniferlu717
![image](https://user-images.githubusercontent.com/40382381/175949516-9a0ef444-2106-445b-82ef-bd7685b2c5a9.png)

Why is the number of reads in the second column equal to the number of reads in the third column? 
In the kraken2 report, this is not the case

**Comment by jenniferlu717** [comment]
The purpose of Bracken is to take all level-based reads above the species level and push them to the species level. This is why the level reads and the total reads are identical. There are no longer reads at lower or higher levels than the species level.
