### ISSUE TITLE
Unable to build a bracken database from a krakenuniq database:

### ISSUE THREAD

**Issue by phlatphish** [jenniferlu717/Bracken#197]
Unable to build a bracken database from a krakenuniq database:

```
> bracken-build -l 75 -t 64 -d /home/projects/redgillite/cjb_metagenome/krakenuniq/db_052422
 >> Selected Options:
       kmer length = 35
       read length = 75
       database    = /home/projects/redgillite/cjb_metagenome/krakenuniq/db_052422
       threads     = 64
 >> Checking for Valid Options...
 ERROR: Kraken2 Database incomplete: /home/projects/redgillite/cjb_metagenome/krakenuniq/db_052422/hash.k2d does not exist
```

The krakenuniq database was successfully used to run krakenuniq.

The database directory contents are:

```
-rw-rw-r-- 1 cjb projects  198 May 24 22:36 database-build.log
-rw-rw-r-- 1 cjb projects 8.1G May 25 03:56 database.idx
-rw-rw-r-- 1 cjb projects 327G May 24 22:36 database.jdb
-rw-rw-r-- 1 cjb projects 327G May 25 23:25 database.kdb
-rw-rw-r-- 1 cjb projects 168K May 25 22:05 database.kdb.counts
-rw-rw-r-- 1 cjb projects  17G May 26 00:53 database.kraken.tsv
-rw-rw-r-- 1 cjb projects 1.3M May 26 00:53 database.report.tsv
-rw-rw-r-- 1 cjb projects 327G May 25 15:24 database0.kdb
-rw-rw-r-- 1 cjb projects 269G May 24 16:05 database_0
-rw-rw-r-- 1 cjb projects 109G May 24 19:28 database_1
drwxrwsr-x 3 cjb projects   26 May 24 10:30 library/
-rw-rw-r-- 1 cjb projects   29 May 24 12:54 library-files.txt
-rw-rw-r-- 1 cjb projects 1.3M May 24 10:38 seqid2taxid.map
-rw-rw-r-- 1 cjb projects 116M May 25 15:26 taxDB
drwxrwsr-x 2 cjb projects  113 May 24 10:16 taxonomy/
```

Compute platform:
```
> uname -a
Linux inbre01.ncgr.org 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```

> krakenuniq --version
KrakenUniq version 0.7.2
Copyright 2017-2018, Florian Breitwieser (fbreitwieser@jhu.edu)
Copyright 2013-2017, Derrick Wood (dwood@cs.jhu.edu) for Kraken

bracken version is 2.7

**Comment by jenniferlu717** [comment]
The newest version should now work with krakenuniq databases.

**Comment by phlatphish** [comment]
v 2.8 looks like it is still looking for a kraken2 type database, even though I specified krakenuniq with the -y parameter

(krakenuniq) cjb@xxx.xxx.org():/data/xxx/db_052422> /home/xxx/build/Bracken/bracken-build -h  
/home/xxx/build/Bracken/bracken-build: illegal option -- h
Usage: bracken_build -k KMER_LEN -l READ_LEN -d MY_DB -x K_INSTALLATION -y K_TYPE -t THREADS
  KMER_LEN       kmer length used to build the kraken database (default: 35)
  THREADS        the number of threads to use when running kraken classification and the bracken scripts
  READ_LEN       read length to get all classifications for (default: 100)
  MY_DB          location of Kraken database
  K_INSTALLATION location of the installed kraken/kraken-build scripts (default assumes scripts can be run from the user path)
  K_TYPE         version of kraken to use (default = kraken2 - other options: kraken, krakenuniq)


(krakenuniq) cjb@xxx.xxx.org():/data/xxx/db_052422> /home/xxx/build/Bracken/bracken-build -k 35 -l 75 -d /data/xxx/db_052422 -x ~/miniconda3/envs/krakenuniq/bin -y krakenuniq -t 32
 >> Selected Options:
       kmer length = 35
       read length = 75
       database    = /data/cjb/db_052422
       threads     = 32
       kraken type = krakenuniq
 >> Checking for Valid Options...
 ERROR: Kraken2 Database incomplete: /data/xxx/db_052422/hash.k2d does not exist
