### ISSUE TITLE
Bracken unable to read krakenuniq report 

### ISSUE THREAD

**Issue by phlatphish** [jenniferlu717/Bracken#198]
I'm unable to build a bracken database from a krakenuniq database ([https://github.com/jenniferlu717/Bracken/issues/197](url)) so i tried the following.

I have a bracken database build on a kraken2 database, which works for bracken processing of kraken2 reports.  

I tried using that kraken2/bracken database to run bracken on a krakenuniq report:

```
> bracken -r 75 -d /home/projects/redgillite/cjb_metagenome/kraken2/database_101721 -i report -o bracken_output_073122 -w bracken_report_073122
 >> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i report -o bracken_output_073122 -k /home/projects/redgillite/cjb_metagenome/kraken2/database_101721/database75mers.kmer_distrib -l S -t 10
PROGRAM START TIME: 08-01-2022 20:38:20
>> Checking report file: report
Traceback (most recent call last):
  File "/home/cjb/miniconda3/envs/bracken/bin/src/est_abundance.py", line 534, in <module>
    main()
  File "/home/cjb/miniconda3/envs/bracken/bin/src/est_abundance.py", line 268, in main
    if level_num != (prev_node.level_num + 1):
AttributeError: 'int' object has no attribute 'level_num'
```

There are a few other open issues on the same subject. Is there any plan to support krakenuniq in bracken?

**Comment by jenniferlu717** [comment]
This has been fixed and updated. The newest version of bracken should work with krakenuniq
