### ISSUE TITLE
export KRAKEN_DB_PATH

### ISSUE THREAD

**Issue by crarlus** [jenniferlu717/Bracken#20]
Kraken has the option to 
> export KRAKEN_DB_PATH

This allows kraken to search for all Kraken DBs in the directories specified in _KRAKEN_DB_PATH_. Could you add this feature to Bracken as well?

Thanks

**Comment by jenniferlu717** [comment]
I'm not certain what this issue is referring to but the newest bracken bash script should allow you to specify the database.
