### ISSUE TITLE
Update version and threshold parameter default for v2.7

### ISSUE THREAD

**Issue by zwallen** [jenniferlu717/Bracken#200]
Hello Jennifer,

I'm currently working with Bracken v 2.7 and happen to notice that the VERSION in the bracken script is still listed as 2.5 and the THRESHOLD variable default value is being set at 10, but the -h parameter lists threshold default as 0. Wanted to give you a heads up about those as that could be confusing for folks.

Best,
Zach

**Comment by jenniferlu717** [comment]
Should be fixed now for the new release! Thanks for noticing.
