### ISSUE TITLE
libexec/classify file not found

### ISSUE THREAD

**Issue by nicoletta87** [jenniferlu717/Bracken#206]
Hi!
I'm working in a conda environment. I installed and used kraken 2, then I installed bracken and I have this error

Can't exec "miniconda3/envs/pylori/libexec/classify": No such file or directory at /miniconda3/envs/pylori/bin/kraken2 line 167.
kraken2: exec error: No such file or directory

I checked in libexec folders and I have not a "classify" file or folder. How it is supposed to be generate?

Line 167 in kraken 2 report

exec $CLASSIFY, @flags, @ARGV;
die "$PROG: exec error: $!\n";

I'm sorry if my question is unclear, I'm not really into bioinformatics.

Thanks!

**Comment by sdauly532** [comment]
I have the exact same problem ，have you figured out what is the problem ?

**Comment by nicoletta87** [comment]
Hi, 
I did a very brutal solution. I found the classify file in another system and then copied it in the libexec folder.

I don't know if I can share this file here with you.

N.

**Comment by sdauly532** [comment]
does that work ？I haven‘t found a way to solve the problem yet .It would be helpful if you could share the file.

**Comment by nicoletta87** [comment]
It worked for me, but I cannote share it because it's not a text file

**Comment by sdauly532** [comment]
could you copy its contents and share it on the GitHub ？Or you can email me ，I think I can’t solve it by myself.  q A q

**Comment by nicoletta87** [comment]
If you want give me your mail adress i can send it to you

**Comment by sdauly532** [comment]
That's awesome！here is my email  ‘yueli2063838060@163.com’ ，thanks again.   ( :
