### ISSUE TITLE
Where is the seqid2taxid.map

### ISSUE THREAD

**Issue by crarlus** [jenniferlu717/Bracken#21]
Hi,
as I am running the script _count-kmer-abundances.pl_ with the new minikraken_8GB [DB](https://ccb.jhu.edu/software/kraken/dl/minikraken_20171019_8GB.tgz)
it throws me the error
> Can't open seqid2taxid.map file - make sure the Kraken database path is defined correctly. No such file or directory

So where can I get the file _seqid2taxid.map_ from?

**Comment by jenniferlu717** [comment]
I just added a download link for the seqid2taxid.map file that works with any standard Kraken databases built in Oct/Nov 2017 and the Minikraken databases. 

The link is on both the Kraken homepage and the Bracken homepage: https://ccb.jhu.edu/software/bracken/
