### ISSUE TITLE
Reducing potential false positive detection

### ISSUE THREAD

**Issue by FCMicrobes** [jenniferlu717/Bracken#22]
Hi all,

Thanks a lot for your efforts developing this tool.
I am using kraken/bracken for taxonomic profiling of metagenomes from various ecosystems and I am currently building databases for bacteria, viruses, fungal and archea using your centrifuge-download tool.

In order to reduce detection of potential false positive taxa could you help me to adopt a rationale     approach to filter the classification?

Is there any way to get a breadth of coverage for each taxa. This might be also a good way to get rid of potential false positives.

If you have any suggestion.

Thanks a lot.

Flo

**Comment by fbreitwieser** [comment]
Hi @FCMicrobes , actually we've just been working on that. KrakenHLL is a drop-in replacement to Kraken that counts the number of unique k-mers for each taxon, and compares it with the total number of k-mers for the taxon in the database. It's available at https://github.com/fbreitwieser/krakenhll . To run, specify the report file on the command line -
 a `kraken-report` call is not needed: 

    krakenhll --db DATABASE --report-file REPORT.OUT > KRAKEN.OUT

Let me know if you have questions.

**Comment by FCMicrobes** [comment]
Hi Florian,
Thanks a lot for your input.
I am exploring krakenhll, I will have some questions very soon !
