### ISSUE TITLE
Error running Nat Protoc example data

### ISSUE THREAD

**Issue by ellisjj** [jenniferlu717/Bracken#238]
Hi,

I've been trying to run the Kraken protocol published in [Nat Protoc 2022](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9725748/), and I'm getting an error when running `bracken`. I've downloaded the program and datasets as described in the protocol, but when I run 

```sh
kraken2 --db k2protocol_db \
    --threads 8 \
    --report SRR14092310.kreport \
    --report-minimizer-data \
    --minimum-hit-groups 3 \
    SRR14092310_1.fasta SRR14092310_2.fasta
bracken -d k2protocol_db -I SRR14092310.kreport -r 100 -l S -t 10 \
    -o SRR14092310.bracken -w SRR14092310.breport
```

I get the following error from `bracken`

```python
>> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i SRR14092310.kreport.original -o SRR14092310.bracken -k /scratch/k2protocol_db/database100mers.kmer_distrib -l S -t 10
PROGRAM START TIME: 09-12-2023 01:44:30
>> Checking report file: SRR14092310.kreport.original
Traceback (most recent call last):
  File "/root/./src/Bracken/src/est_abundance.py", line 554, in <module>
    main()
  File "/root/./src/Bracken/src/est_abundance.py", line 323, in main
    elif main_lvls.index(level_id[0]) >= branch_lvl:
                         ~~~~~~~~^^^
IndexError: string index out of range
```

I'm using `kraken2` v2.1.3 and `bracken` version v2.8 but have also tried with v2.1.1 and v2.6.2 respectively (the exact versions mentioned in the protocol paper) with the same error.

The first few lines of the kraken report generated by the above command look like:

```
 6.08   1641723  1641723  0       0       U       0       unclassified
93.92  25357745  84737  188067967       540818          1       root
93.61  25272997  430  186883655       537056  1       131567    cellular organisms
93.59  25267994  400567  186737948       513420          2           Bacteria
86.61  23385501  66848  169741507       252735  D1      1783272       Terrabacteria group
86.37  23318123  185106  169170266       249831  P       1239            Firmicutes
```

The sixth column is blank for root and Bacteria, which I believe is causing the IndexError I'm seeing. I also see that in the `bracken` repository there is an example report under `sample_data/sample_test.report` which has the same format as my `kraken2` report but without blank columns. If I manually replace the blanks with "D" and any number that's in column 6 with a "-", `bracken` will successfully run, but I don't know if that's a reasonable thing to do.

My question is, is this an error in the way `bracken` is processing the kraken report or an error in the output of `kraken2`? Alternatively, is there something wrong with the commands I'm using? I've been trying to follow the protocol paper exactly, so I'm not sure why I'm getting this error, any guidance would be appreciated

Thanks

**Comment by jenniferlu717** [comment]
Thanks for investigating this. I suspect something changed in the database as Bacteria should be under D, The root will not cause a problem with the blank but the Bacteria one will.

I'm adding a  fix now that should account for missing ranks.
