### ISSUE TITLE
Extract certain reads belonging to certain taxa.  

### ISSUE THREAD

**Issue by luzhang321** [jenniferlu717/Bracken#246]
Hi :) 

I ran kraken2.1.2 & bracken for my mice gut microbiome shotgun metagenomic analysis. 
Since there are some non-bacteria reads in the bracken output. I would like to keep only the bacteria reads as my interest for the downstream analysis. 

I found out that kraken2 provides a tool called `extract_kraken_reads.py`. But I didn't find similar tools in Bracken. So I was wondering whether it is okay that I extracted the bacteria reads based on the kraken2 result. Or are there any similar tools in Bracken doing similar work? 

The extracting code I used for extracting bacteria reads based on kraken2 output.
`KrakenTools-1.2/extract_kraken_reads.py -k $filename".output.txt" -s1 $filename".new_kneaddata_paired_1.fastq" -s2 $filename".new_kneaddata_paired_2.fastq" -o bacteria_reads/$filename"_1.bac.fasta" -o2 bacteria_reads/$filename"_2.bac.fasta" -t 2 --include-children -r /sbidata/projects/lzhang/2022_mice/Output/Kneaddata_custom_database_output/$filename".report.txt"`

Thanks so much!

**Comment by jenniferlu717** [comment]
I am the author for KrakenTools (including extract_kraken_reads.py) and Bracken but you cannot extract reads from Bracken output. Bracken estimates read counts but does not reassign individual reads. The best option would just to be using extract_kraken_reads as you have already run the program.
