### ISSUE TITLE
/kraken_db/library directory

### ISSUE THREAD

**Issue by NielQC** [jenniferlu717/Bracken#25]
Hi all, 

I'm having troubles trying to figure out where is the 'library' directory located, necessary for the first step of Bracken's workflow. I could download Kraken standard database following the manual, and the later analyses and reports also ran well. The problem comes when I try to run Bracken cause I can't locate the `/kraken_db/library` directory with the fasta files. How can I get this directory? Thanks in advance.

**Comment by NielQC** [comment]
The problem was the `clean` command of Kraken, that removes the `library` directory and other files.

**Comment by jenniferlu717** [comment]
Ah yeah, you need to generate the Bracken input files before you run the `clean` command.
