### ISSUE TITLE
bracken-build - syntax error: unexpected end of file

### ISSUE THREAD

**Issue by nicholascdove** [jenniferlu717/Bracken#252]
Is there a syntax error in the `braken-build` script?
`bracken-build -d ./vir_db -t 12` # both the Bracken and Kraken2 folders are in the `PATH`
```
 >> Selected Options:
       kmer length = 35
       read length = 100
       database    = ./vir_db
       threads     = 12
       kraken type = kraken2
 >> Checking for Valid Options...
 >> Creating database.kraken [if not found]
/git/Bracken/bracken-build: line 229: syntax error: unexpected end of file
```
Any idea of what is going on? I looked at `bracken-build`, but I couldn't find a syntax error. Thanks!

**Comment by nicholascdove** [comment]
needs a `fi` on line 189.

**Comment by nicholascdove** [comment]
Actually, the above is not true. Not totally sure what is going on, but it looks like there is a syntax error in `d26b268`. Upon reverting back to `835c65b`, everything works as expected.

**Comment by balaram26** [comment]
this issue seem not fixed, i downloaded most recent git nd still get the issue during bracken build:
>bracken-build -d new_krakne_db/ -t4 -k 20
 >> Selected Options:
       kmer length = 20
       read length = 100
       database    = new_krakne_db/
       threads     = 4
       kraken type = kraken2
 >> Checking for Valid Options...
 >> Creating database.kraken [if not found]
../bin/bracken-build: line 229: syntax error: unexpected end of file`
