### ISSUE TITLE
##Bracken metagenomics abundance

### ISSUE THREAD

**Issue by penglbio** [jenniferlu717/Bracken#26]
I am little confused by counting the abundance of species in metagenomics-wide sequencing. If we used the read counts as the abundance of the species, shall we normalize it. Liking the RNA-seq, maybe need to divide the length, because the length of the each microbial genome is different. So I want to ask if the result of Bracken report can be used  to compared diversity of the species abundance directly.

**Comment by jenniferlu717** [comment]
If you do want to use the output of the Bracken report to estimate the **number of organisms** and not just number of reads, you will need to normalize by average genome length for the species. Bracken only provides the estimated read counts originating from a species, not the estimate organism numbers.

**Comment by penglbio** [comment]
but In your paper, according to my understanding, The figure 5,you just use the read counts to  estimate of species abundance. I think the bacteria genome length of each specie  is different. so just using read counts may be not correct completely
