### ISSUE TITLE
Bracken Taxonomic Level

### ISSUE THREAD

**Issue by austenrowell** [jenniferlu717/Bracken#264]
Hello,

I am using Bracken for a metaviromic analysis. A few of the viruses are showing in my kreport above my threshold of 10, but when I run bracken they are not showing in the breport. When I look at my kreport it shows a -- at the taxonomic level for these viruses although they should be species. When I look in the database at the ktaxonomy.tsv file it lists the virus as S1. 

I am wondering if there is a command or argument where bracken will let me see all reads above my threshold or if there is a file I can tweak that will allow these viruses to be called at a species level and appear in the breport.

Thank you for any help and advice!
-Austen

**Comment by jenniferlu717** [comment]
If you want those specific viruses to appear at species level, i think you can change their parent label to G1 and change their levels to S. That may be the easiest to include them without breaking Bracken

**Comment by austenrowell** [comment]
Jennifer thank you for you help! That worked perfectly!
