### ISSUE TITLE
Running Kraken2 + Bracken on multiple FASTQs per sample (each belonging to read group with its own read length)

### ISSUE THREAD

**Issue by hermidalc** [jenniferlu717/Bracken#272]
Wondering how to properly run Kraken2 + Bracken with multiple FASTQs per sample, where each FASTQ pair belongs to a read group (i.e. lane) with its own distinct read length. Do I simply run each FASTQ pair through the pipeline separately setting the appropriate read length for Bracken and then sum the resulting abundance estimates to aggregate it to the sample level at the end?

**Comment by hermidalc** [comment]
Wondering too if there's a different option where if I have a single FASTQ pair with reads of different lengths, is there an easier way to set the read length parameter in Bracken to something appropriate? Like the longest read length in the FASTQ or the mean read length?

**Comment by jenniferlu717** [comment]
Yes running each individually through bracken and then summing the read counts per species (for example) would be most appropriate. Sorry for the late reply
