### ISSUE TITLE
Bracken-build: line 231: syntax error: unexpected end of file error

### ISSUE THREAD

**Issue by MaxvanGils** [jenniferlu717/Bracken#286]
Hi, novice bioinformatician here with a small question:

I want to use Bracken for the relative abundance calc for some Kraken2 classified data. I already have the classification done, and now want to include Bracken for the results.  I have downloaded both Kraken2 and Bracken into one conda environment, and both in separate for testing, but to no avail.

However, when I want to run the bracken-build command, i get the following error:
```
bracken-build -d your_kraken_db -t 35 -l 900
 >> Selected Options:
       kmer length = 35
       read length = 900
       database    = your_kraken_db
       threads     = 35
       kraken type = kraken2
 >> Checking for Valid Options...
 >> Creating database.kraken [if not found]
.../miniforge3/envs/bracken/bin/bracken-build: line 231: syntax error: unexpected end of file
```

I am running Bracken v2.9, and no later version is available in Conda. How could I fix this issue?

My thanks in advance!

**Comment by MaxvanGils** [comment]
Nevermind, I figured it out!

**Comment by luwenyi111** [comment]
> Nevermind, I figured it out!

how you figured it out? I meet the same error

**Comment by MaxvanGils** [comment]
@luwenyi111 So I looked deeper into some similar issues and fixes placed by jenniferlu717 and others, and found that a line in the bracken-build file can be changed and then it works...


![download](https://github.com/user-attachments/assets/e4ab3f8f-27ac-4666-b3ea-b9ec59290b52)
