### ISSUE TITLE
Error running est_abundance.py script

### ISSUE THREAD

**Issue by donthu** [jenniferlu717/Bracken#3]
I am getting the following error when I run est_abundance.py script. Could you please help me fix this error. Thank you.

<pre>
python bracken-2016-06-02/Bracken-master/est_abundance.py -i ../2016-05-05-kraken/sample1.kraken.report -k database_kmer_dist_file.txt -o sample1.bracken.report > sample1.bracken.out 2>&1
</pre>

**Error message**
<pre>
PROGRAM START TIME: 06-02-2016 20:55:53
Traceback (most recent call last):
  File "bracken-2016-06-02/Bracken-master/est_abundance.py", line 433, in <module>
    main()
  File "bracken-2016-06-02/Bracken-master/est_abundance.py", line 305, in main
    P_A = float(est_g_reads)/float(all_genome_reads)
ZeroDivisionError: float division by zero
</pre>

**Comment by jenniferlu717** [comment]
I added a line that will skip cases where that happens. I'm not sure why it's detecting 0 estimated reads, but try the newest version?

**Comment by donthu** [comment]
Thank you for making necessary changes to the code. It works fine now. I could now run without any other errors!
