### ISSUE TITLE
[Question] Using Bracken on datasets with varying read lengths

### ISSUE THREAD

**Issue by Stan-Derksen** [jenniferlu717/Bracken#30]
Hello,

I'm attempting to estimate abundance on a metagenome dataset with varying read lengths due to adapter/quality trimming etc. My reads range from 100bp to 300bp. Would Bracken work if I'd for example use the average, min or max read length?

Kind regards,
Stan

**Comment by jenniferlu717** [comment]
I would use the minimum read length. When we tested Bracken originally, we did find that 31mers did not reflect where a full read would land in the taxonomic tree. Instead, we used 75mers for our 150bp paired reads. We did not use 150bp as it was not guaranteed that the two pairs were exactly from the same location, but 75mers performed better for our set of 150mers. 

As long as you go with the minimum read length, you can capture how those reads will distribute. I think it would be interesting to see how different the results would be if you chose 100bp vs. 300bp. but I haven't tried that.

**Comment by Stan-Derksen** [comment]
Thanks for your quick reply! I agree it'd be interesting to see the differences between different values for read length, I will experiment some, thank you!
