### ISSUE TITLE
problem with using more than one level from est_abundance.py script

### ISSUE THREAD

**Issue by balathl** [jenniferlu717/Bracken#31]
python est_abundance.py -i kraken.sample1.report -k OUTPUT_database75mers.kraken_cnts.TXT -o OUTPUT_FILE_all_levels.TXT --level "D,P,G,S"
usage: est_abundance.py [-h] -i INPUT -k KMER_DISTR -o OUTPUT
                        [-l {D,P,C,O,F,G,S}] [-t THRESH]
est_abundance.py: error: argument -l/--level: invalid choice: 'D,P,G,S' (choose from 'D', 'P', 'C', 'O', 'F', 'G', 'S')

Is there anyway to include more levels at same command?

Bala

**Comment by jenniferlu717** [comment]
Not currently but I'm not sure what kind of results you're looking for by adding in multiple levels?

You can just run the command multiple times to get the abundance estimates at the different levels. I don't believe the command would take that much time.

**Comment by balathl** [comment]
![image](https://user-images.githubusercontent.com/29751682/37783887-3905cabc-2dff-11e8-898c-2d9748d2bcaa.png)

I am aiming my final results in this format. Any comments will be useful

**Comment by jenniferlu717** [comment]
You can just concatenate the output files from each Bracken run. They will give you the taxid, rank, and percentages. You would have to then generate the taxpath and the taxpathsn columns but otherwise, concatenating the output would give you most of what you want.

**Comment by balathl** [comment]
ok. Thanks! This was the first time i am using bracken. great tool :)

Could you suggest any improvements in the below commands??

#dont run again#kraken-build --standard --db /wrk/bjam/challenge/filtered/KrakenDB
#run again with other samples#kraken --db KrakenDB --paired --quick --unclassified-out UNCLASSIFIED_sample01_test --classified-out CLASSIFIED_sample01_test --out-fmt paired --output stdout_sample01_test --preload --check-names --fastq-input sample01_F_filt.fastq sample01_R_filt.fastq --threads 16
#run again with other samples#kraken-report --db /wrk/bjam/challenge/filtered/KrakenDB stdout_sample01 > kraken.sample1.report
perl count-kmer-abundances.pl --db /wrk/bjam/challenge/filtered/KrakenDB --read-length=75 --threads=16 stdout_sample01 > database75mers.kraken_cnts
python generate_kmer_distribution.py -i database75mers.kraken_cnts -o OUTPUT_database75mers.kraken_cnts.TXT
python est_abundance.py -i kraken.sample1.report -k OUTPUT_database75mers.kraken_cnts.TXT -o OUTPUT_FILE_species.TXT
python est_abundance.py -i kraken.sample1.report -k OUTPUT_database75mers.kraken_cnts.TXT -o OUTPUT_FILE_genus.TXT --level G
echo done

My fastq reads were 151 basepairs.

Thanks in advance!

Bala

**Comment by jenniferlu717** [comment]
I think the commands look fine from my end.
