### ISSUE TITLE
Doubt in bracken predictions

### ISSUE THREAD

**Issue by balathl** [jenniferlu717/Bracken#32]
Hi Jennifer,

The following output from Bracken is little confusing for me as the kraken assigned reads and estimated reads from bracken is same in every rows. I thought it will vary as bracken uses an additional estimate step. Correct me if i understood something wrong.

(my_biotools_bracken) [bjam@c307 filtered]$ head OUTPUT_FILE_species.test.TXT
name	taxonomy_id	taxonomy_lvl	kraken_assigned_reads	added_reads	new_est_reads	fraction_total_reads
Campylobacter sp. RM16704	1500960	S	994	0	994	0.00463
[Enterobacter] lignolyticus	1334193	S	299	0	299	0.00139
Sphingobium sp. YBL2	484429	S	805	0	805	0.00375
Candidatus Phytoplasma mali	37692	S	258	0	258	0.00120
Streptomyces collinus	42684	S	68	0	68	0.00032
Alkalitalea saponilacus	889453	S	1032	0	1032	0.00480
Lactobacillus ginsenosidimutans	1007676	S	1072	0	1072	0.00499
Streptomyces lincolnensis	1915	S	19	0	19	0.00009
Maribacter sp. HTCC2170	313603	S	17634	0	17634	0.08206
(my_biotools_bracken) [bjam@c307 filtered]$ tail OUTPUT_FILE_species.test.TXT
Wolbachia endosymbiont of Cimex lectularius	246273	S	92	0	92	0.00043
Cupriavidus sp. USMAHM13	1389192	S	201	0	201	0.00094
Lactobacillus acetotolerans	1600	S	803	0	803	0.00374
Clostridium butyricum	1492	S	2096	0	2096	0.00975
Maribacter sp. T28	1836467	S	2811	0	2811	0.01308
Mycobacterium kansasii	1768	S	10619	0	10619	0.04941
Streptomyces venezuelae	54571	S	4534	0	4534	0.02110
Elizabethkingia miricola	172045	S	345	0	345	0.00161
Tessaracoccus flavescens	399497	S	1942	0	1942	0.00904
Bacillus sp. IHB B 7164	1827146	S	34	0	34	0.00016

I used the below steps to obtain the above result:

Any explanation to understand this will be useful! Thanks.

Bala

**Comment by jenniferlu717** [comment]
Can you send me your report file (both Kraken and Bracken reports) to my email jlu26@jhmi.edu

**Comment by balathl** [comment]
I sent the report file to your email Id. Thanks for the reply.

Bala
