### ISSUE TITLE
I can not run count-kmer-abundance.pl script

### ISSUE THREAD

**Issue by JingQiuyu** [jenniferlu717/Bracken#33]
When I try to run 'perl count-kmer-abundance.pl', here comes error as follows:

Can't locate List/MoreUtils.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at count-kmer-abundances.pl line 22.
BEGIN failed--compilation aborted at count-kmer-abundances.pl line 22.

Should I update my perl or is there any solutions to that?

**Comment by fbreitwieser** [comment]
Hi @JingQiuyu , please use cpan to install the List::MoreUtils module. More info: http://www.cpan.org/modules/INSTALL.html

**Comment by JingQiuyu** [comment]
@fbreitwieser ,Thanks for your help. I solved the problem by installing the List::MoreUtils module as described in your web link.
