### ISSUE TITLE
xrealloc: cannot allocate

### ISSUE THREAD

**Issue by narsapuramvijaykumar** [jenniferlu717/Bracken#35]
Hi Team,

When I am trying to run the step 2a of braken, it gives me below error.
Command : kraken -db=/home/user/vj/kraken_db/ --fasta-input --threads 10 $(find -L /home/user/vj/kraken_db/library -name "*.fna" -exec cat {} +) > /home/user/vj//kraken_db/database_braken.kraken
ERROR : xrealloc: cannot allocate 18446744071562067968 bytes (57344 bytes allocated)
find: ‘cat’ terminated by signal 13

Also, I ran below command,
kraken -db=/home/user/vj/kraken_db/ --fasta-input --threads 10 /home/user/vj/kraken_db/library/bacteria/library.fna > /home/user/vj/kraken_db/database_braken.kraken
Is this right command..? and It ran for more than 24hrs and gave no result, I have to manually kill it to proceed further.

Need some inputs. Thanks in advance

Regards,
Vijay N

**Comment by jenniferlu717** [comment]
it looks like its having trouble allocating the memory for the database? How large is your database?

**Comment by jenniferlu717** [comment]
This issue should be fixed by the release of kraken2.0. Bracken itself can be run using Kraken2, just replace any kraken commands with kraken2 (and kraken-build replaced with kraken2-build) :https://github.com/DerrickWood/kraken2
