### ISSUE TITLE
seqid2taxid.map file

### ISSUE THREAD

**Issue by Ligiamunoz** [jenniferlu717/Bracken#39]
Hi I have done my Classifying a Full Kraken Database but when I run the comands, appears this error, I moved the database.kraken to many folders but the error continues.

admins@pc1[src] perl count-kmer-abundances.pl --db /media/admins/RESPALDO/minikraken_20171019_8GB --read-length 75 database.kraken > database75mers.kraken_cnts 
Reading nodes.dmp ... Done
Calculating taxon depths ... Done
Can't open seqid2taxid.map file - make sure the Kraken database path is defined correctly. No such file or directory

**Comment by jenniferlu717** [comment]
Did you also download the seqid2taxid.map file for the minikraken databases?

**Comment by Ligiamunoz** [comment]
Thanks I did it and I can get the abundance. I have other question, what is the function of "DustMasked MiniKraken DB 8GB"? because I only download "MiniKraken DB_8GB" and now "seqid2taxid.map", my classification is wrong? I need "DustMasked Minikraken"?

**Comment by jenniferlu717** [comment]
It won't be wrong necessarily but the dustmasked version removed all low-complexity sequences. If your sample has a low-complexity sequence, then that sequence might be misclassified.
