### ISSUE TITLE
error in est_abundance.py

### ISSUE THREAD

**Issue by najoshi** [jenniferlu717/Bracken#4]
Hello,
So I am trying to run Bracken using my Kraken output and I can get to the est_abundance step and that script crashes with this error:

PROGRAM START TIME: 06-07-2016 20:47:51
Traceback (most recent call last):
  File "est_abundance.py", line 436, in <module>
    main()
  File "est_abundance.py", line 264, in main
    for child_node in curr_node.children:
AttributeError: 'int' object has no attribute 'children'

Here is the command I used:

python est_abundance.py -i ../data/PGM-6-RNA_56.kraken.out -k kmer_dist.txt -o bracken.abundance.out

Any idea what could be wrong?

- Nik.

**Comment by jenniferlu717** [comment]
Did you use the kraken report and not just the kraken output file? This only works with the kraken report

**Comment by najoshi** [comment]
Yes, that was the problem. Thanks. :)
