### ISSUE TITLE
database.kraken wrong

### ISSUE THREAD

**Issue by yi1873** [jenniferlu717/Bracken#40]
An error "Usage: classify [options] <fasta/fastq file(s)>" occurred  when  running  the following command  " kraken --db=/path/kraken.db --fasta-input --threads=10 <( find -L library -name ".fna" -o -name "*.fa" -o -name "*.fasta" -exec cat {} + ) > database.kraken "

**Comment by jenniferlu717** [comment]
Apologies for the late response, I somehow missed seeing this issue. The usage error will come up if its having issues with the find command and unable to find the FASTA files making your library.

I would try testing that command by doing:
``<( find -L library -name ".fna" -o -name ".fa" -o -name ".fasta" -exec cat {} + )  > TESTING.FASTA``
