### ISSUE TITLE
A simple question:

### ISSUE THREAD

**Issue by xgnusr** [jenniferlu717/Bracken#41]
A simple question:
Is 'bracken' compatible with 'kraken2.0' ???

**Comment by jenniferlu717** [comment]
Yes, the code runs in the exact same way. Just make sure you generate a report when running kraken 2.0 (using the --report flag I believe). The results are nearly identical to Kraken v1.0. We did a few tests before releasing Kraken v2.0 to make sure nothing big changed.

**Comment by jenniferlu717** [comment]
At a later date, we may incorporate some of the statistics you need for Bracken directly in the database building of Kraken v2.0 but we have yet to begin working on that.
