### ISSUE TITLE
Does bracken-build work?

### ISSUE THREAD

**Issue by ghbore** [jenniferlu717/Bracken#42]
Hi, developers, I was noticed that bracken is successive abundance estimator for kraken report. Since I have created my own kraken database, I should build bracken db by myself too. But I check the **bracken-build** script, and it seems to do nothing. Is it still under development?

**Comment by jenniferlu717** [comment]
The bracken-build script itself does not work, but refer to the manual/website to build/use bracken itself.  https://ccb.jhu.edu/software/bracken/ 

I was hoping to create a bracken-build script that can do all of the necessary steps without requiring the user to run each one individually, but I have yet to write the script yet. Apologies for the confusion.
