### ISSUE TITLE
Error using a Custom Database - [Step 2a] 

### ISSUE THREAD

**Issue by MaryoHg** [jenniferlu717/Bracken#44]
Dear jenniferlu (and Bracken team),

I used a custom database with Kraken2 (see [here](https://github.com/DerrickWood/kraken2/issues/25)).
So, to estimate the abundance, I need first to 
>Step 2a: Search all library input sequences against the database 

But when I ran the script, the output is an empty file. 

>kraken2 --db=${bigDB} --threads=12 <( find -L library -name "*.fna" -o -name "*.fa" -o -name "*.fasta" -exec cat {} + )  > database.kraken
find: ‘library’: No such file or directory 
Loading database information... done.
0 sequences (0.00 Mbp) processed in 0.001s (0.0 Kseq/m, 0.00 Mbp/m).
  0 sequences classified (-nan%)
  0 sequences unclassified (-nan%)

So, my approach was to concatenate each 'library.fna' file inside each folder inside $bigDB/library:
pwd=/home/user/bin/kraken2/bigDB/library
> $ cat $pwd/archaea/library.fna $pwd/virus/library.fna $pwd/fungi/library.fna > $pwd/bigDB.fna

Then I ran 'again' step 2a, using:
>  $ kraken2 --db $bigDB --threads 12 $pwd/bigDB.fna > $pwd/database.kraken

Does this work flow make sense?
I've already make it through Bracken using some Kraken2 report-test files but...

I really appreciate your comments.

Thanks,
Maryo.

**Comment by jacodela** [comment]
Hello,

I'm having a similar issue: I'm able to run step 1 using a custom database using Kraken 1, yet when I run 

`kraken --db /tmp/global2/jdelacuesta/Kraken --fasta-input --threads=10 <( find -L /ebio/abt3_projects/databases/Kraken/library -name "*.fna" -o -name "*.fa" -o -name "*.fasta" -exec cat {} + ) > /ebio/abt3_projects/vadinCA11/data/V11/Bracken/braken_classification/database.kraken`

I get the following error

> classify: malformed fasta file - expected header char > not found
0 sequences (0.00 Mbp) processed in 0.029s (0.0 Kseq/m, 0.00 Mbp/m).
  0 sequences classified (-nan%)
  0 sequences unclassified (-nan%)

I was wondering whether this has something to do with:
* Using several genomes with the same taxid, or
* Adding non-complete genomes (i.e. genomes fragmented in multiple contigs) to the Kraken database.

Thanks,

**Comment by jenniferlu717** [comment]
Hello, 

Sorry for the late response. None of those issues should be causing it. 

Its actually the find portion of that command line that for some reason, needs to be changed? The original find statement worked for me but now I need to use the following:
`find -L library \( -name "*.fna" -o -name "*.fa"  -o -name "*.fasta" \) -exec cat {} +` 

If the above works, then just add the `\(` and `\)` (including spaces before/after) into the command line and it should work well. 

``

**Comment by MaryoHg** [comment]
Hi, Jennifer.

I was able to run the code using what you said:

``$ kraken2 --db=${bigDB} --threads 12 <( find -L $bigDB/library/ \( -name "*.fna" -o -name "*.fa" -o -name "*.fasta" \) -exec cat {} + ) > test.kraken``
>Loading database information... done.
11329 sequences (2079.23 Mbp) processed in 97.046s (7.0 Kseq/m, 1285.51 Mbp/m).
  11270 sequences classified (99.48%)
  59 sequences unclassified (0.52%)

THANKS for your help. 

Maryo.
