### ISSUE TITLE
count-kmer-abundances.pl is very slow with kraken2 databases of millions of sequences

### ISSUE THREAD

**Issue by thbtmntgn** [jenniferlu717/Bracken#45]
Hi,

I'm able to build kraken databases with an higher number of genomes/sequences now that Kraken2 is released, is much faster and requires less RAM and storage.

I succeed to build a kraken2 database and I'm now looking for generate bracken statistics. My problem is that count-kmer-abundances.pl seems very slow.

After 2-3 days running not even 2% of taxon depths are calculated: `1.59%; line     265825 / 16727249`. At this rhythm it will take more than 100 days to process.

I'm using all my CPUs and RAM is not a problem as I built the kraken2 database successfully.

Do you think there is a way to improve speed for count-kmer-abundances.pl?

**Comment by thbtmntgn** [comment]
Awesome! I'm looking forward to test the updates!

I'm using 64 CPUs

**Comment by jenniferlu717** [comment]
The newest github commit contains the new scripts. The new scripts will allow you to the run that step much faster. (for one of the databases I tested, with 20 threads, the runtime of that steps decreases from 52 minutes to 18 minutes). 

I am hoping to make it even faster, but still working out those details. will be providing a new Bracken 2.0 release soon.

**Comment by jenniferlu717** [comment]
Thanks for noticing the error in the README. 

kmer2read_distr doesn't output that much when done on command line. It does update over time which read is being read, so this could be because on command line, it returns and rewrites over to update counts. 

I'll add a flag for --verbose that will suppress this.
