### ISSUE TITLE
How can I add (or get) the complete taxon levels to a specific Bracken output file?

### ISSUE THREAD

**Issue by MaryoHg** [jenniferlu717/Bracken#46]
Hi, dear Bracken Team.

I'm aware Bracken outputs are separated by each taxon level for a specific option used in the ``est_abundance.py`` script:

I ran this command:
``$ est_abundance.py -i sampleA.report -k $kmer_100mers -l P -o SampleA.phyla`` 
> Note: to get the sampleA.report I used the --report-zero-counts option with ``kraken2`` script to be able to join this output with sampleB.phyla output file. I have two samples to be analyzed with Bracken.

This is what I get:
``$ head -4 SampleA.phyla``

name|fraction_total_reads
----|--------------------
Proteobacteria|0.60962
Spirochaetes|0.00085
Ascomycota|0.00368

I want to be able to add the complete taxon (for this level, I just need to add the (D)omain level, right?) like this:
``$ head -4 SampleA.phyla``

name|fraction_total_reads
----|--------------------
d__Bacteria_p__Proteobacteria|0.60962
d__Bacteria_p__Spirochaetes|0.00085
d__Eukaryota_k__Fungi p__Ascomycota|0.00368

**Is there a non-manually way to achieve this data format for all taxon levels?**
I think it would be a mpa-format like, but I can't achieve this goal.
I think this format is very useful to statistics and graphics analysis.

Please, I would appreciate your help.
**¡Thank you all!**

**Comment by jenniferlu717** [comment]
I think the kreport2mpa.py program provided with Bracken might be useful to what you're looking for?

**Comment by MaryoHg** [comment]
Hi, @jenniferlu717.
Thanks for your reply earlier.

I actually tried to use that script before asking and after reading [#18](https://github.com/jenniferlu717/Bracken/issues/18). I couldn't answer my question though.

One of your answer says this:
>Added a script that can be used to convert the Bracken/Kraken reports to mpa. Please let me know if you find any issues with it.

I test the script ``kreport2mpa.py`` but I only achieve to convert a ``kraken2 --report`` file to a mpa-style, which can be accomplished using ``--report `` and ``--use-mpa-style`` options within kraken2 itself.

Actually, while showing ``-h`` for that script, it says that it require a --report file from kraken but Bracken.
``kreport2mpa.py -h``
> -r R_FILE, --report-file R_FILE, --report R_FILE
                        **Input kraken report file for converting**

So, my question remains.
Something like this [(same thread)](https://github.com/jenniferlu717/Bracken/issues/18)
> I am able to use it on kraken output but not on the bracken output which is split at a taxonomic level. I was wondering if it was possible to have an mpa format from Bracken


Please, I kindly appreciate your time and response.
I am sorry If I'm not seeing what you want me to, Jenn.

Thanks.

**Comment by ramay** [comment]
Hi Jennifer, 
Is there a way to specify where the  _braken report is saved. At the moment it is storing this file in the same folder as the input kraken report. I would like to store them in another directory where the bracken report is stored. I am using snakemake and want to keep results of each rule in a separate directory. 
Thanks!
Hena
