### ISSUE TITLE
Is it possible to use Bracken with Kraken1 output?

### ISSUE THREAD

**Issue by semiramisCJ** [jenniferlu717/Bracken#47]
Is it possible to transform the Kraken1 reports to a Kraken2 format? Or is it necessary to re-run the classification step with Kraken2 before using Bracken?

**Comment by jenniferlu717** [comment]
I'm not sure I understand your issue? Bracken works with both Kraken 1 and Kraken 2 results. If you already have a Kraken 1 report and Bracken files for the Kraken 1 database, then Bracken works fine.

However, if you want to use Kraken 2, which has a smaller database and a faster classification, you need to remake the database and reclassify your sample and generate the bracken files for the Kraken2 database. 

The results between Kraken1 and Kraken 2 are similar.

**Comment by jenniferlu717** [comment]
The input to Bracken is the kraken-report output. Just run kraken-report --db MY_DB SAMPLE.KRAKEN > SAMPLE.KREPORT

**Comment by semiramisCJ** [comment]
Thank you very much for your help!! :smile:
