### ISSUE TITLE
Using Braken with dustmasked Mini-kraken

### ISSUE THREAD

**Issue by apredeus** [jenniferlu717/Bracken#48]
Hello Jennifer, 

I wanted to use Bracken with dustmasked 8Gb mini-kraken DB. My reads are 150 bp paired-end. The files provided at Bracken download sites are for 75, 100 and 200 bp k-mers. So, my questions are 

1) Do I need to make a separate 150 bp k-mer distribution file? Or would it be OK for me to use 100 or 200 bp files? 
2) In order to make your own k-mer distribution file, as far as I understand, you need the original sequences that were used to create the database. Do you know where I can get these sequences? Do I need to use dustmasked sequences or original ones? 

BTW, the key script referred in the manual as _estimate_abundance.py_, but must have been renamed later into _est_abundance.py_. Just thought I'd let you know. 

Thank you in advance!

**Comment by jenniferlu717** [comment]
I would use the 75bp one. The sequenced themselves are the default Kraken database as of last year I believe. Which should include the refseq complete genomes for bacteria and archaea. But we also will be releasing a minikraken for Kraken v. 2.0 soon.
