### ISSUE TITLE
Miss Treshold conversion

### ISSUE THREAD

**Issue by bioinfornatics** [jenniferlu717/Bracken#5]
Dear,

There is a missing conversion at line 352. When user set a treshold with -t option there is no conversion from string to int.
https://github.com/jenniferlu717/Bracken/blob/master/est_abundance.py#L352

I fixed the bug by casting arg.tresh in int:
print("    >>> Threshold: %i " % int(args.thresh))

Hope it will be helpfull,

**Comment by jenniferlu717** [comment]
Made the fix, Thanks.
