### ISSUE TITLE
Errors with bracken-build

### ISSUE THREAD

**Issue by thbtmntgn** [jenniferlu717/Bracken#50]
1) I'm getting the following error message when trying to use `bracken-build` script even if kraken/kraken2 are installed and in my PATH.

`bracken-build -d ${KRAKEN_DB} -t ${THREADS} -k ${KMER_LEN} -l ${READ_LEN} 
`
```
/home/ec2-user/tools/bracken-2.1/bracken-build: line 76: [: ==: unary operator expected
User must first install kraken or kraken2 and/or specify installation directory of kraken/kraken2 using -x flag
```
It seems to be working when using `-x` parameter.

2) When using `-x` parameter I'm getting the following error message even if seqid2taxid.map exists: 

`bracken-build -d ${KRAKEN_DB} -t ${THREADS} -k ${KMER_LEN} -l ${READ_LEN} -x ${KRAKEN_INSTALLATION}`

```
seqid2taxid.map does not exist  For usage, please run: 
     kmer2read_distr --help
```

It seems to be working when `-d` parameter is an absolute path only

**Comment by jenniferlu717** [comment]
ah thank you for checking. I'll fix the script ASAP. I just wrote the bash syntax wrong for the first instance.

**Comment by jenniferlu717** [comment]
Fixed the bracken-build script. I think both should work now, but please let me know if they do not.
