### ISSUE TITLE
Question on abundance estimation

### ISSUE THREAD

**Issue by snayfach** [jenniferlu717/Bracken#52]
My understanding is the Braken estimates the % of reads in a sample assigned to a clade at a given taxonomic rank. Does Braken normalize at all for genome length - or the # of kmers in the database from each clade? Or does it just report the % of reads?

Thanks,
Stephen

**Comment by jenniferlu717** [comment]
It does not normalize for genome length. There are several cases in which genomes within a single clade have varied genome lengths so we did not find it as useful to normalize. It reports the reads estimated to be from within each clade.

**Comment by jenniferlu717** [comment]
That is part of the basis for the tool itself. It is using a probability model given how reads classify to determine where reads belong.
