### ISSUE TITLE
Small README errors

### ISSUE THREAD

**Issue by thbtmntgn** [jenniferlu717/Bracken#53]
In README header: `https:/` is missing in just before `/ccb.jhu.edu/software/bracken/`

In README --> HARD VERSION --> Step 1b: `/src/kmer2read_distrib`should be `/src/kmer2read_distr`

**Comment by jenniferlu717** [comment]
Sorry I'm rather behind on all of this, will fix the README ASAP

**Comment by jenniferlu717** [comment]
just updated
