### ISSUE TITLE
combine_bracken_outputs.py --names = comma-delimited

### ISSUE THREAD

**Issue by nick-youngblut** [jenniferlu717/Bracken#55]
This is a small thing, but the `combine_bracken_outputs.py` help doc doesn't state that the names (`--names`) should be provided as comma-delimited. So, I wasn't sure if I needed to provide a file with 1 name per line, a comma-delim list, or something else. I had to look at the script to determine this.

**Comment by jenniferlu717** [comment]
I updated the help information for that command line option. Thanks for noticing this!
