### ISSUE TITLE
combine_bracken_outputs.py not py3 compatible

### ISSUE THREAD

**Issue by nick-youngblut** [jenniferlu717/Bracken#56]
Running `combine_bracken_outputs.py` in a py3 environment generates the following error:

```
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/afe44be5/bin/combine_bracken_outputs.py", line 151, in <module>
    main()
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/afe44be5/bin/combine_bracken_outputs.py", line 112, in main
    elif taxid != sample_counts[name].keys()[0]:
TypeError: 'dict_keys' object does not support indexing
```

This is fixed by changing:

```
elif taxid != sample_counts[name].keys()[0]
```

to:

```
elif taxid != list(sample_counts[name].keys())[0]
```

So, adding `list()` should make this script py3 compatible.

**Comment by jenniferlu717** [comment]
I made the change, hope it works now!

**Comment by apcamargo** [comment]
https://github.com/jenniferlu717/Bracken/blob/master/analysis_scripts/combine_bracken_outputs.py#L133

Line 133 still has this issue

**Comment by marsfro** [comment]
Hello everyone! I solved this problem just by activated py2 environment:
conda activate py2
If you don't have python 2 environment, create:
https://gist.github.com/stormwild/f89d48b34aa3255903f8d59bae98c639

**Comment by nick-youngblut** [comment]
>Hello everyone! I solved this problem just by activated py2 environment:

py2 is depreciated and should no longer be used
