### ISSUE TITLE
bracken-build not able to detect Kraken1 database

### ISSUE THREAD

**Issue by kevinVervier** [jenniferlu717/Bracken#57]
Hello,

I am trying to run 'bracken-build' on a Kraken-1.0 database, and I get an error related to files missing for Kraken-2.0 database: 'ERROR: Kraken2 Database incomplete: my_kraken_db/hash.k2d does not exist'

Then, I tried to add -x flag with path to where the kraken script can be found:
'braken-build -d my_kraken_db/ -t 8 -k 31 -l 200 -x /usr/local/kraken-1.0/scripts/kraken' and got the following error: 'User must first install kraken or kraken2 and/or specify installation directory of kraken/kraken2 using -x flag'
I tried different paths '/usr/local/kraken-1.0', '/usr/local/kraken-1.0/scripts' and '/usr/local/kraken-1.0/scripts/kraken', and got the same message.
Could you help me finding what I am missing?
Cheers,
Kevin

**Comment by jenniferlu717** [comment]
Hi apologies. The program is looking for the folder where kraken/kraken2 are command lines that can be run. So you shouldn't specify the full path to kraken itself, but the folder where the kraken command line is available. 

If you do not specify -x, then it tries to run kraken or kraken2. If kraken2 is available, it will look for a kraken2 database.

Let me know if that helps? You could manually modify the bracken-build file to have the script check for kraken before kraken2 (by modifying lines 77-80)

**Comment by kevinVervier** [comment]
I see what happened: the path to kraken folder needs to include a final '/'.
Now it works fine. Thank you.
