### ISSUE TITLE
How does the fraction_total_reads calculated in bracken report?

### ISSUE THREAD

**Issue by haoye2015** [jenniferlu717/Bracken#66]
Hi Jenifer,

I just tested bracken for species level abundance estimation with default cutoff at 10. The report file contains "kraken_assigned_reads", "added_reads" ," new_est_reads" as well as "fraction_total_reads"。However, the value in the column "new_est_reads" divided by the value in column "fraction_total_reads"  are not equal in different rows.  For example, I pasted top 3 rows of the report as following.  In the first row,  clostridioides difficile   368/0.00058 = 634482.758.   While, in the second row, Botrytis cinerea  81/0.00013 = 623076.92.  It seems neither 623076.92 nor 634482,758 are the total number of reads. I wonder how does the value "fraction_total_reads" calculated?  Doesn't it comes from "new_est_reads" divied by the number.total_reads?

Best

Hao 

The first 4 rows of the a demo bracken report.

name | taxonomy_id | taxonomy_lvl | kraken_assigned_reads | added_reads | new_est_reads | fraction_total_reads
Clostridioides difficile | 1496 | S | 12 | 356 | 368 | 0.00058
Botrytis cinerea | 40559 | S | 81 | 0 | 81 | 0.00013
Mycoplasma capricolum | 2095 | S | 25 | 37 | 62 | 0.0001

**Comment by jenniferlu717** [comment]
I believe its including the unclassified reads, which is not included in that output file but is in both the original and updated bracken report file.

**Comment by haoye2015** [comment]
Hi Jennifer, I have sent  kraken2, bracken report to you through email jlu26@jhmi.edu  

Thank you very much .

**Comment by robmaz** [comment]
Hi Jennifer, was this issue resolved? Because we have noticed the same discrepancies and were wondering ...

**Comment by robmaz** [comment]
I notice that there is this old PR #59 which may be related?

**Comment by jenniferlu717** [comment]
What happens is that frac_total_reads was calculated from the pre-rounded reads/total. I just changed it to use the rounded reads/total instead. Hopefully this will fix the issue.

**Comment by Martincapt** [comment]
Hi Jennifer, I'm trying to find out if there is way for me see the number of reads discarded and number of species below the threshold and above.  I have both the bracken report and the bracken output file but i can't locate this desired information.

**Comment by jenniferlu717** [comment]
That information was printed to the system output when Bracken was run. You can compare the total number of reads from the Bracken report to that in the Kraken report. The Bracken output file might show you which species were below the threshold if you just sort by number of Kraken assigned reads.
