### ISSUE TITLE
is there a way to extract [bracken_added_reads] from my raw fasta file?

### ISSUE THREAD

**Issue by withered-leaf** [jenniferlu717/Bracken#67]
Hi Jennifer,

I have noticed that Bracken Output File has 3 columns counts result: [Kraken assigned reads],[Added reads] and [new_est_reads].
The [kraken assigned reads] is matched to the infomation in kraken.report file , so I can easily extract the reads of my target taxonomy/species by the readID-classified correspondence.
However, ,[Added reads] is produced by Bayesian Reestimation, and there is no intermediate documents.I need to extract the sequences of these reads for subsequent validation but  I can't find a way to locate them. 

for example:
name    taxonomy_id     taxonomy_lvl    kraken_assigned_reads   added_reads     new_est_reads   fraction_total_reads
Staphylococcus aureus   1280    S       138     3182    3320    0.00021
The final counts is 3320, but I only obtain 138 reads from input fasta via  kraken.report file , how can I extract the other 3182 added_reads?
Thanks a lot!

**Comment by jenniferlu717** [comment]
The calculation for reestimating reads is not on a per read basis. Reads end up "higher" in the taxonomy with Kraken if all of their kmers are found in every genome within that root. e.g. if a read matches multiple Mycobacterium genomes, then the read is labeled as Mycobacterium by Kraken. Bracken is using probabilities to calculate how many of those reads belong to each of the individual genomes (with species abundance estimation). 

e.g. if 100 reads are labeled as Mycobacterium, Bracken might tell you that it is most probable that 50 came from M.tb while 50 came from M.avian. But Bracken will not tell you which 50.
