### ISSUE TITLE
error running est_abundance.py

### ISSUE THREAD

**Issue by adambazinet** [jenniferlu717/Bracken#7]
Hi,

I'm encountering some errors when running est_abundance.py. The error is different depending on which version of Python I use:

>python --version
Python 3.5.1 :: Anaconda 4.0.0 (64-bit)

>python est_abundance.py -i kraken_output -k kmer_distr_250mers.txt -o bracken_output
PROGRAM START TIME: 11-14-2016 18:43:15
Traceback (most recent call last):
  File "est_abundance.py", line 456, in <module>
    main()
  File "est_abundance.py", line 211, in main
    report_vals = process_kraken_report(line)
  File "est_abundance.py", line 135, in process_kraken_report
    int(split_str[1])
IndexError: list index out of range

>python --version
Python 2.7.3

>python est_abundance.py -i kraken_output -k kmer_distr_250mers.txt -o bracken_output
PROGRAM START TIME: 11-14-2016 18:45:32
Traceback (most recent call last):
  File "est_abundance.py", line 456, in <module>
    main()
  File "est_abundance.py", line 284, in main
    for child_node in curr_node.children:
AttributeError: 'int' object has no attribute 'children'

I'm attaching the input files so you can replicate the issue. At the moment I don't know if it's a problem with my input, a bug with Bracken, if I'm not using the right Python version, etc.

thanks,
Adam

[Bracken_input_files.zip](https://github.com/jenniferlu717/Bracken/files/590227/Bracken_input_files.zip)

**Comment by jenniferlu717** [comment]
You need to generate the kraken report files using kraken-report from the kraken direct output. The program works only on the report files, not the kraken output.

I need to add an error check to ensure people use the kraken report files, but I haven't had a chance to do that yet.

**Comment by adambazinet** [comment]
Ah, I did miss that, thanks!
