### ISSUE TITLE
Prebuilt Minikraken databases seem to all lack /library directory

### ISSUE THREAD

**Issue by swlong** [jenniferlu717/Bracken#70]
Am I missing something, or do the all the prebuilt Minikraken databases, for Kraken v1 or Kraken v2, lack the /library directory, thus leaving them unsuitable for use with Bracken 2.2? 

Apologies in advance if this has an obvious solution.

**Comment by swlong** [comment]
Sorry, using the prebuilt bracken database files appears to be working... but I am guessing I can't build new bracken database files off the Minikraken databases since they've been "cleaned" of the library files.

**Comment by jenniferlu717** [comment]
The minikraken databases are provided as complete databases without the need to download/store/install the library files. The prebuilt bracken files are provided similarly. If you would like a particular minikraken file for bracken, let me know and I can generate it/provide it.

**Comment by swlong** [comment]
Thanks, I appreciate it. I think I'm good for now, I just needed an extra cup of coffee yesterday I think. :)
