### ISSUE TITLE
compatibility with kraken2 NCBI nt and env_nt reference libraries

### ISSUE THREAD

**Issue by slambrechts** [jenniferlu717/Bracken#73]
Dear Jennifer,

I was wondering whether bracken is compatible with custom kraken2 databases such as the NCBI `nt `or NCBI `env_nt` libraries made available through kraken2-build?

Cheers,

Sam

**Comment by jenniferlu717** [comment]
It is comptible although I think it may be a bit too slow at the moment. If you are okay with waiting a couple days...i think it would finish but Im hoping to work on making it more parallel/optimized in the next couple months

**Comment by jenniferlu717** [comment]
The newest Bracken version is a lot faster than previously. I'm not sure how long it will take for nt, but I will be testing that asap

**Comment by jenniferlu717** [comment]
Using 35 threads, the NCBI nt build with bracken was about 9 hours. Hope that helps. I'm going to close this issue for now.
