### ISSUE TITLE
Low Kraken2 mapped reads

### ISSUE THREAD

**Issue by xingpel** [jenniferlu717/Bracken#75]
Hi, 
I'm using kraken2 to generate reads to feed bracken for abundance estimation. But it seems the kraken2's read count somehow does not add up correctly. I have about 40million reads and 6.48% not mapped, which showed correctly logged at the end of the program completion. 

But the mapped reads from the Kraken2 report seems far from making the rest of 93.52%, where did the mapped reads go?

From the Kraken2 report:
"
  6.48  2647460 2647460 U       0       unclassified
  0.03  10670   4212    R       1       root
  0.01  6031    0       R1      131567    cellular organisms
  0.01  5594    0       D       2759        Eukaryota
...(the rest of lines at 2nd column of all D l add up definitely less than 1 million reads.)
"

**Comment by jenniferlu717** [comment]
Is this the report produced by Bracken? 

Did you specify a threshold?

**Comment by jenniferlu717** [comment]
Since this is a Kraken2 issue (and not a Bracken issue), I'm going to close this but hopefully we can resolve this on the Kraken 2 github page.
