### ISSUE TITLE
Number of reads distributed

### ISSUE THREAD

**Issue by marin-e** [jenniferlu717/Bracken#77]
Dear Jennifer, 

I just tested bracken and I have a question about the number of reads distributed by bracken : the command give me the output `Reads distributed: 10928503` but when I do the sum of the rows of the 'added_reads' column in the .bracken file I obtain 10 928 456. Can you explain me this difference?

Thank you

**Comment by jenniferlu717** [comment]
Its likely a rounding issue. The added_reads column is rounded, but the actual calculations may distribute 10 reads (for example) into 2.4, 2.4, 2.2, and 3 reads, which would round to 2,2,2, and 3 (9 reads). Does that make sense? Apologies for this. It doesn't make sense to give fractions of reads to any specific species.
