### ISSUE TITLE
kmer2read_distr:   can't use nonpositive threads

### ISSUE THREAD

**Issue by yjk555** [jenniferlu717/Bracken#78]
Can anyone tell me what happened to result in this error? The codes I am running is 
./bracken-build -d /KRAKEN2 -threads 32 -k 35 -l 100 -x /kraken2_installation
I reported the error "kmer2read_distr:   can't use nonpositive threads"  2 hours later when I ran the code. Don't know how to fix this. Any comments or suggestions will be appreciated.

**Comment by jenniferlu717** [comment]
Can you try with just -t 32 instead of -threads 32 (i don't think the script takes the full -threads option)

**Comment by yjk555** [comment]
> Can you try with just -t 32 instead of -threads 32 (i don't think the script takes the full -threads option)

Many thanks for your advice, now I have figured out the problem.
