### ISSUE TITLE
How to set the threshold for bracken estimate abundance?

### ISSUE THREAD

**Issue by yjk555** [jenniferlu717/Bracken#79]
Hi, Jennifer:
I found that the threshold setting in bracken estimate abundance really affect my results, for example, when I set 10(default), the most abundant genus in archaea is Sulfolobus while it is Methanobrevibacter by setting -t 30. However, according to the mpa-report in Kraken2, the most abundant genus in archaea is Methanobrevibacter,, so this may suggest the default threshold 10 is not suitable for the estimate abundance of my reports. Besides, the most abundant genus in archaea in rumen should be  Methanobrevibacter as many papers reported. So, do you have any suggestion towards my issue about how to set a threshold for estimate abundance?
Many thanks,
Jiangkun

**Comment by jenniferlu717** [comment]
I think it should be a factor of the number of reads in your sample and the expected diversity, so setting a default is difficult. 

In cases where there's a largely diverse sample, 10 reads has shown to be a decent threshold. This threshold is also the number of reads at the strain/genome level required, not at the genus/species levels.
