### ISSUE TITLE
Error with custom database

### ISSUE THREAD

**Issue by ajaybabu27** [jenniferlu717/Bracken#8]
Hi,

I tried performing "Step 2a: Search all library input sequences against the database" using a custom kraken database that I have built and got the following error message:

Loading database... complete.
Processed 14 sequences (13275013 bp) ...terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

The command I ran is:

kraken --preload --db=/sc/orga/scratch/kumara22/kraken/db_custom_cdiff_all_clonal_parsnp --fasta-input --threads=24 <( find -L /sc/orga/scratch/kumara22/kraken/db_custom_cdiff_all_clonal_parsnp/library -name "*.fna" -exec cat {} + )  > /sc/orga/scratch/kumara22/kraken/database.kraken

I am running this command with 24 cores and 100 Gb Memory in a single node. 

Do let me know if I am missing something on my end. 

Ajay.

**Comment by fbreitwieser** [comment]
Hi Ajay, 
What's the size of your custom database?
Florian

**Comment by ajaybabu27** [comment]
The size of my custom database is 95 GB.

**Comment by jenniferlu717** [comment]
This may be an issue you need to direct to Derrick Wood (the author of Kraken)

**Comment by ajaybabu27** [comment]
I was able to figure it out. The issue was not allocating more memory. 

Now I am stuck at step 2b when I run this command:
perl count-kmer-abundances.pl --db=/tmp/db_custom_cdiff_all_clonal_parsnp --read-length=100 /tmp/database.kraken > /tmp/database100mers.kraken_cnts

I get the following output:
Reading nodes.dmp ... Done
Calculating taxon depths ... Depth already defined for 2000015! at count-kmer-abundances.pl line 223.

It script stops with no data written to the output file (database100mers.kraken_cnts). 

Any pointers would be appreciated. 

Thanks,
Ajay.

**Comment by ajaybabu27** [comment]
Hi,

Any updates on this issue ? 

Thanks,
Ajay.

**Comment by jenniferlu717** [comment]
Sorry about this. The script you are having issues with is written by Florian, I'll ask him to help you.

**Comment by fbreitwieser** [comment]
Can you provide the lines in your nodes.dmp that have the taxon 2000015 in the first or second column? I think you might have multiple parents for one taxon, and Kraken only works when you have one parent for each child.

**Comment by ajaybabu27** [comment]
Hi Florian,

You are right, I mislabelled one of the nodes that resulted in violation of the DAG tree nomenclature. Everything works well from my end. Thanks for your assistance ! 

Cheers,
Ajay.

**Comment by fbreitwieser** [comment]
Great it works now, Ajay!
