### ISSUE TITLE
Error in braken-build documentation

### ISSUE THREAD

**Issue by kyclark** [jenniferlu717/Bracken#80]
The page 

https://ccb.jhu.edu/software/bracken/index.shtml?t=manual

Has under Step 1 this command:

./bracken-build -d ${KRAKEN_DB} -threads ${THREADS} -k ${KMER_LEN} -l ${READ_LEN} -x ${KRAKEN_INSTALLATION}

But the threads option name is just `-t` otherwise it tries to use `hreads` as the value for "threads" rather than the option I pass in. You could alter the bash script to accept the long name, but it might be easier just to correct the docs.

Thanks!

Ken

**Comment by jenniferlu717** [comment]
Thanks for noticing this issue! I'll make the fix now.

**Comment by jenniferlu717** [comment]
Fixed! If you notice any other discrepancies, please let me know. I appreciate it.
