### ISSUE TITLE
multiple read length

### ISSUE THREAD

**Issue by lancer-lu** [jenniferlu717/Bracken#81]
@jenniferlu717 
Dear jenniferlu,

My read is paired-end(150bp), but it'll be better to merge them for percise alignment, but there exsits a problem that some of the paired-end reads can't be merged, so my read length  is distributed between 150 and 300bp. 
 I  see in the readme.md, bracken easy version has some ways to tackle reads with multiple read length, but my data have many kinds of  read length.
 I have read your paper,  length r is used to generate a database that the length of kmers is r, which is equal to the read length, then we can know how many k-mers  are unique to genome Si. So can I set it to the minimum?

Thanks in advance ,
Regards,
 Lu

**Comment by jenniferlu717** [comment]
I would use read length of 150. For paired reads, we use the length of one individual read, not the combined reads.

**Comment by lancer-lu** [comment]
> I would use read length of 150. For paired reads, we use the length of one individual read, not the combined reads.

Thank you！I have solve my problem.
