### ISSUE TITLE
bracken conda install breaks kraken2

### ISSUE THREAD

**Issue by osilander** [jenniferlu717/Bracken#82]
Not sure whether this is the right place to post, but when I use conda to install bracken, it breaks my current kraken2 install. After installing bracken, if I remove kraken2 and reinstall it this fixes the issue, but then I need different conda environments to run bracken and kraken2 in...

The error after I have kraken2 installed, then install bracken, then try to run kraken2:

~/miniconda3/libexec/classify: invalid option -- 'H'
Usage: classify [options] <fasta/fastq file(s)>

Detailed conda install messages attached.

[bracken_break.txt](https://github.com/jenniferlu717/Bracken/files/3685314/bracken_break.txt)

**Comment by BioinformaticsBro** [comment]
Dr. Silander, fancy seeing you outside of the ONT community forums! 

I had a similar problem when installing Bracken with conda. Installing Bracken will install Kraken2.2 as a dependency, so you may have two versions of Kraken that conflicts. 

What solved my problem was to backup the Kraken database, delete everything, install Bracken with conda (which also installs Kraken), then restore the kraken database folder.

**Comment by osilander** [comment]
Ha. Ha. Ha.
Thanks, I'll try that. Basically: just rely on bracken to install everything?
conda claims it's only installing kraken 1.1.1 (not kraken2), but maybe there's still an issue.

**Comment by BioinformaticsBro** [comment]
Conda installs both Kraken1 and Kraken2, but they shouldn't conflict with each other. 

What conda channel are you using? I installed Bracken just last month and this is current my environment. 

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blast                     2.5.0                hc0b0e79_3    bioconda
boost                     1.70.0           py27h9de70de_1    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bracken                   2.5              py27hc9558a2_0    bioconda
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py27_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jellyfish                 1.1.12               h6bb024c_1    bioconda
kraken                    1.1.1           pl526h6bb024c_0    bioconda
kraken2                   2.0.8_beta      pl526h6bb024c_0    bioconda
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
libidn2                   2.1.1                h14c3975_0    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libunistring              0.9.10               h14c3975_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.4           py27h95a1406_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.2.3                   py27_0    conda-forge
popt                      1.16                          1    bioconda
python                    2.7.15            h5a48372_1009    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rsync                     3.1.3             hed695b0_1002    conda-forge
setuptools                41.2.0                   py27_0    conda-forge
sqlite                    3.29.0               hcee41ef_1    conda-forge
taxonkit                  0.5.0                         0    bioconda
tk                        8.6.9             hed695b0_1002    conda-forge
wget                      1.20.1               h90d6eec_0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge

```

**Comment by BioinformaticsBro** [comment]
Yeah, basically let conda do everything. I recommend using a fresh environment so it doesn't clash with any of your other installs (it shouldn't though).

`conda create --name new_bracken_env -c bioconda bracken`

I don't know how we got on before conda.

**Comment by osilander** [comment]
Not sure, but just using bracken for the install seemed to make both bracken and kraken2 work. Now working on getting the database satisfactory for bracken. We'll see.

**Comment by jenniferlu717** [comment]
I'm afraid that I'm not the one that maintains the bracken conda install, but let me know if you continue to see any other issues?
