### ISSUE TITLE
Error in manuscript?

### ISSUE THREAD

**Issue by larssnip** [jenniferlu717/Bracken#83]
Right after Equation (2) you write N_Si is the number of k-mers of length r uniquely assigned to genome Si. Should this be reads, not k-mers? It makes more sense. First, a k-mer of length r should be an r-mer. Second, you use r as read length elsewhere. Finally, the denominator in the Equation is the number of reads in Si (not k-mers), and the numerator should not exceed this value. In the following paragraph you also write k-mers, but is this correct?

**Comment by jenniferlu717** [comment]
N_x is the number of r-mers assigned to x, so the subscript is what those r-mers are assigned to. 

k-mers is a bit ambiguous in that paragraph, I admit. I used it as a common way to denote a subscript of a general sequence, but yes, it would make more sense to say r-mer. It is the number of reads uniquely assigned.

**Comment by larssnip** [comment]
OK, thanks for the clarification

LS

**Comment by taniagmangolini** [comment]
What is the difference between N_Si e K_Si (Equation 3)?
