### ISSUE TITLE
 AttributeError : Bracken

### ISSUE THREAD

**Issue by Annie-msi** [jenniferlu717/Bracken#84]
Hi,
I am trying to run Bracken from a kraken2 output with following command
 bracken -d ~/GG -i all_CF.kraken2 -l S -o all_CF.bracken
Error i am getting:
>> Checking for Valid Options...
 >> Running Bracken
      >> python src/est_abundance.py -i all_CF.kraken2 -o all_CF.bracken -k /home/plar    sen/jahan036/GG/database100mers.kmer_distrib -l S -t 0
PROGRAM START TIME: 11-14-2019 03:24:43
Traceback (most recent call last):
  File "/home/plarsen/jahan036/.conda/envs/Bracken/bin/src/est_abundance.py", line 468    , in <module>
    main()
  File "/home/plarsen/jahan036/.conda/envs/Bracken/bin/src/est_abundance.py", line 285    , in main
    for child_node in curr_node.children:
AttributeError: 'int' object has no attribute 'children'

I have build the Bracken data base with following command
 bracken-build -d ~/GG  (here GG is the custom database for kraken2)
I am using Conda for installation

Thanks

**Comment by jenniferlu717** [comment]
Hello, I suspect you're trying to run Bracken with the Kraken output and not the Kraken report output. 

Bracken needs the report, not the direct output.

**Comment by Annie-msi** [comment]
Awesome, it worked.
Thanks a lot.
Was wondering is there any visualization tools that can take the Bracken output for plotting results? like Krona?

**Comment by jenniferlu717** [comment]
Bracken automatically creates a _bracken.kreport file. You can input that into my kreport2krona.py script found on my github repository under jenniferlu717/KrakenTools

**Comment by Annie-msi** [comment]
Thank you so much!
