### ISSUE TITLE
No library folder in custom database 

### ISSUE THREAD

**Issue by LeonardosMageiros** [jenniferlu717/Bracken#85]
Hi, 

I have used a custom library (https://monash.figshare.com/projects/Metagenomics_Index_Correction/65534) of Kraken2 to interogate my metagenomes. All good so far. 
Now I want to run Bracken on the Kraken reports. 
The database I have contains 3 files (hash.k2d, opts.k2d and taxo.k2d). 
I believe the issue is that there is no library folder as when I am running the bracken-build command giving as an input the folder where the 3 files are located I get:

ERROR: Database library /home/ubuntu/leo_1/tools/Kraken2/db/library does not exist

Is there any way to generate the library folder from the db binary files? 

Thank you in advance for your time. 
Leonardos

**Comment by jenniferlu717** [comment]
Unfortunately, no, you will need to ask the person that generated the original database to make the database.kraken file or the subsequent bracken files.
