### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by TCA-fanli** [jenniferlu717/Bracken#86]
Hi,

I'm trying to run Bracken with output from kraken2, but getting this error:
```
$ bracken -d /share/kraken2/Standard -i 104.Standard.kraken2.txt -o 104.Standard.bracken -r 150
 >> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i 104.Standard.kraken2.txt -o 104.Standard.bracken -k /share/kraken2/Standard/database150mers.kmer_distrib -l S -t 0
PROGRAM START TIME: 12-30-2019 18:57:34
Traceback (most recent call last):
  File "/share/Bracken/src/est_abundance.py", line 468, in <module>
    main()
  File "/share/Bracken/src/est_abundance.py", line 271, in main
    [mapped_taxid, mapped_taxid_dict] = process_kmer_distribution(line,lvl_taxids,map2lvl_taxids)
  File "/share/Bracken/src/est_abundance.py", line 99, in process_kmer_distribution
    [g_taxid,mkmers,tkmers] = genome_str.split(':')
ValueError: too many values to unpack
```

I ran kraken2 as follows:
`kraken2 --db /share/kraken2/Standard --threads 16 --paired --output 104.Standard.kraken2.out --report 104.Standard.kraken2.txt 104.R1.filtered.fastq 104.R2.filtered.fastq`

`104` is an arbitrary sample ID, not relevant here. 

The database directory `/share/kraken2/Standard/` has the `database150mers.kmer_distrib` file. 

I have attached the input `104.Standard.kraken2.txt` file. Not sure if that file is broken, or if the issue is somewhere else.

Thanks!
Fan
[104.Standard.kraken2.txt](https://github.com/jenniferlu717/Bracken/files/4010730/104.Standard.kraken2.txt)

**Comment by davidbio** [comment]
Same here.
I tried running bracken-build with -t 1, but it didn't help.

**Comment by jenniferlu717** [comment]
I cannot quite seem to recreate the error. If you send both the report and the databaseXmers.kmer_distrib files (those shouldn't be too big), I can test it.

**Comment by fanli-gcb** [comment]
Attaching my database150mers.kmer_distrib

I agree with David's comment about the extraneous semi-colons that are being created and perhaps not expected by the `genome_str.split(':')` line, but not sure where this got introduced. Similarly, I am using the standard kraken2 database build.

[database150mers.kmer_distrib.gz](https://github.com/jenniferlu717/Bracken/files/4036780/database150mers.kmer_distrib.gz)

**Comment by jenniferlu717** [comment]
I fixed it with the latest update. 
So you don't have to rerun all of the steps. All you need to do is run:
`python generate_kmer_distribution.py -i **database150mers.kraken** -o **database150mers.kmer_distrib**`

**Comment by fanli-gcb** [comment]
Confirming that the latest update fixes this. Thanks!
