### ISSUE TITLE
new_est_reads is identical to kraken_assigned_reads

### ISSUE THREAD

**Issue by feargalr** [jenniferlu717/Bracken#87]
Hey, 

I've run Bracken for the first time and haven't had any errors, except the results it's outputting are basically just the same as Kracken with species that don't meet the read threshold removed. I'm running it on neonatal infant gut metagenomes which would be relatively low diversity but still odd that no reads are distributed at all. See log + command below. 

Any advice?

python ~/programs/Bracken/src/est_abundance.py -k ~/kraken2_standard_db/kraken2_standard_20200108/database75mers.kmer_distrib -i standard_db.report.txt -o bracken.txt -l 'S' -t 100

PROGRAM START TIME: 01-13-2020 04:08:07
BRACKEN SUMMARY (Kraken report: ERR525691.standard_db.report.txt)
    >>> Threshold: 100
    >>> Number of species in sample: 2754
          >> Number of species with reads > threshold: 310
          >> Number of species with reads < threshold: 2444
    >>> Total reads in sample: 18872238
          >> Total reads kept at species level (reads > threshold): 13093407
          >> Total reads discarded (species reads < threshold): 46550
          >> Reads distributed: 0
          >> Reads not distributed (eg. no species above threshold): 952329
          >> Unclassified reads: 4779952
BRACKEN OUTPUT PRODUCED: ERR525691.bracken.txt
PROGRAM END TIME: 01-13-2020 04:08:07

**Comment by hughcross** [comment]
Hi,

I am getting the same result. No reads are distributed with any of my samples. I even set the threshold to 1, just in case that would help.

**Comment by jenniferlu717** [comment]
@feargalr and @hughcross please email me your kraken report and your kmer distribution file (both should be fairly small) and I can take a look (jlu26@jhmi.edu)

**Comment by mziegler12** [comment]
Hey there,

i have a similar issue. Reads are perfectly distributed if i use the minikraken db but not if i use the downloaded NCBI db. The KRAKEN2 NCBI db was build with:
`kraken2-build --standard --db NCBI_all_taxa --threads 24 --no-masking`

After the exiting with 
`unexpected FTP path (new server?) for na`
I used the troubleshooting protocol from  https://github.com/DerrickWood/kraken2/issues/226 by adding
`"if ( $full_path =~/^na/){
         next
      }`
to rsync_from_ncbi.pl

the database build was finished successfully. If i use this db with kraken2 and bracken, the reads are not distributed:
`BRACKEN SUMMARY (Kraken report: ./I19-1063-01_S1_kraken2_NCBI_report)
    >>> Threshold: 10 
    >>> Number of species in sample: 16363 
          >> Number of species with reads > threshold: 852 
          >> Number of species with reads < threshold: 15511 
    >>> Total reads in sample: 11940691
          >> Total reads kept at species level (reads > threshold): 8791089
          >> Total reads discarded (species reads < threshold): 8289
          >> Reads distributed: 0
          >> Reads not distributed (eg. no species above threshold): 2823080
          >> Unclassified reads: 318233
BRACKEN OUTPUT PRODUCED: I19-1063-01_S1_kraken_NCBI_report_bracken`

if i use the minikraken db with kraken2 and bracken reads are getting redistributed:
`BRACKEN SUMMARY (Kraken report: I19-1063-01_S1_kraken2_minikraken_report)
    >>> Threshold: 10 
    >>> Number of species in sample: 11781 
          >> Number of species with reads > threshold: 427 
          >> Number of species with reads < threshold: 11354 
    >>> Total reads in sample: 11940691
          >> Total reads kept at species level (reads > threshold): 9414146
          >> Total reads discarded (species reads < threshold): 3422
          >> Reads distributed: 1996039
          >> Reads not distributed (eg. no species above threshold): 22697
          >> Unclassified reads: 504387
BRACKEN OUTPUT PRODUCED: I19-1063-01_S1_kraken2_minikraken_report_bracken`

do you have any suggestions?

All the best
Martin

**Comment by jenniferlu717** [comment]
@mziegler12 What are the command lines you used to build the bracken database and run bracken?

Also, if you can show some of your report file here?

**Comment by mziegler12** [comment]
Hi @jenniferlu717,

this is how i build the bracken db:
```
/Bracken-2.5/bracken-build \
   -d NCBI_all_taxa \
   -t 16 \
   -k 35 \
   -l 300 \
   -x kraken2-master/
```

afterwards running bracken:
```
/Bracken-2.5/bracken \
-d /BioInformatics/soft/kraken2-master/NCBI_all_taxa \
-i ./I19-1063-01_S1_kraken2_NCBI_report \
-t 10 -r 300 -l S \
-o I19-1063-01_S1_kraken_NCBI_report_bracken.txt
```

And finally the report files one for minikraken db and one for the NCBI_all_taxa db. Thank you for the super fast answer.
[I19-1063-01_S1_kraken2_minikraken_report.txt](https://github.com/jenniferlu717/Bracken/files/5621341/I19-1063-01_S1_kraken2_minikraken_report.txt)
[I19-1063-01_S1_kraken2_NCBI_report.txt](https://github.com/jenniferlu717/Bracken/files/5621342/I19-1063-01_S1_kraken2_NCBI_report.txt)


All the best
Martin

**Comment by mziegler12** [comment]
Hi @jenniferlu717,

i think i figured it out. My `database.kraken` file was corrupt. If it exists, `bracken-build` will not generate a new one. So i deleted  `database.kraken` and the database setup seems to work now.

**Comment by jenniferlu717** [comment]
Ah thank you. Apologies for not getting back to you. I need to make an error catch to see if the database.kraken file is empty but i haven't yet...hm.
