### ISSUE TITLE
Read to Taxa Mapping

### ISSUE THREAD

**Issue by davidbio** [jenniferlu717/Bracken#88]
Hi,

I am currently evaluating Bracken 2.5 and it looks very promising to improve abundance estimations from plain Kraken2 output.
Is it possible to retrieve the read names for each OTU/taxa from Bracken?
This feature is very helpful when working with Kraken because it allows processing certain reads in particular. Think of assembly and gene prediction for a species if the metagenome shows enough coverage.

Keep up the good work!

Best,
David

**Comment by davidbio** [comment]
I was looking for this #67 when I searched if the topic already existed, right? :(

**Comment by jenniferlu717** [comment]
I think the only thing you could do is get the potential reads that belong to a particular species based on the reads that were assigned to its parent taxons. The extract_kraken_reads.py program here: https://github.com/jenniferlu717/KrakenTools will allow you to extract reads assigned to a species **AND** all of the species' parent taxons.
