### ISSUE TITLE
How to specify location for saving   _bracken report

### ISSUE THREAD

**Issue by ramay** [jenniferlu717/Bracken#89]
Hi Jennifer,
Is there a way to specify where the _braken report is saved. At the moment it is storing this file in the same folder as the input kraken report. I would like to store it in another directory where the bracken report is stored. I am using kreport2mpa on this file in a later step in a snakemake file.

Thanks!
Hena

**Comment by jenniferlu717** [comment]
I dont think i have it set so users can specify it but I can provide an copy of the program that will allow that. I should have one available tomorrow morning

**Comment by ramay** [comment]
Thanks Jennifer! 
I have managed to make it work but if you can provide me with the change that will be great!
Hena

**Comment by jenniferlu717** [comment]
I added an option for it into both scripts. 

Using the shell script, `bracken -w NEWREPORT` will let you change the report name
Using the python script, `bracken --out-report NEWREPORT` will change the report name. 

By default, it will just add "__bracken" to the report name, but now there is the option to change it/specify the full name.
