### ISSUE TITLE
Bracken Manuscript

### ISSUE THREAD

**Issue by dnbh** [jenniferlu717/Bracken#9]
Hi,

I seem to be unable to find many implementation details regarding your work on the Bracken paper. Do you have source code for how you selected the genomes you chose to use?

Additionally, what parameters were used to construct your Kraken database? In particular, what kmer size and minimizer size did you use?

Thanks!

**Comment by jenniferlu717** [comment]
We manually chose the genomes we ran our test sets on. We started with all finished genomes in an old iteration of the NCBI microbe database and added in a few finished genomes that were suspected to be in our test samples l. Using finished genomes is recommended to minimize false positives.  

We used the default for the kraken database, which are the parameters optimized for in the original Kraken paper by Wood et.al.

**Comment by dnbh** [comment]
You manually chose genome by genome for thousands of genomes? You didn't filter by annotation, file name, or sequence name?

**Comment by jenniferlu717** [comment]
Sorry, I wasn't clear about the database chosen. This is the text extracted from our paper: https://peerj.com/articles/cs-104/,

This may help explain our genome choices more. 

> The second (“large”) database contains all genomes used in the synthetic and spike-in experiments, as well as a broad background of bacterial genomes. In particular, it includes all complete bacterial and archaeal genomes from RefSeq as of 25 July 2014 (archived at ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_refseq), which total 2596 distinct taxa, plus those i100 genomes that were not present in the RefSeq data. (We excluded draft genomes because they often contain vector sequences or other contaminants.) We also added the nine genomes used in our skin bacteria spike-in experiment (described below) resulting in a total of 2635 distinct taxa

**Comment by dnbh** [comment]
Thank you!

How did you distinguish complete and draft genomes?

**Comment by jenniferlu717** [comment]
If you go to the link, the draft ones are in a separate folder.

**Comment by dnbh** [comment]
Thank you!

I fetched all the genomes from the Bacteria folder, avoiding the draft genomes, and have a total of 5242 genomes instead of 2596. Can you explain that discrepancy?

**Comment by jenniferlu717** [comment]
Did you use the old refseq or the new one? The new refseq has 5000 genomes while the old one has around 2600 (the summary.txt in the old refseq Bacteria folder lists around 2600 genomes)

**Comment by dnbh** [comment]
I did, yes. Thank you.

I found 5242 genomes in the ftp directory and 2634 accessions in the summary.txt file.

Of those 2634, 2615 are contained in the set of genomes, with 19 missing. Did you encounter this problem?

**Comment by jenniferlu717** [comment]
The exact genomes we used are in the Supplementary Table 1 for the Bracken paper. 

We excluded some of the genomes at the end of the ftp file. 
For some accessions, there are multiple genomes, which is why there are 5000+ genome files, but only ~2600 accessions. 

Please refer to the Supplementary Table
