### ISSUE TITLE
how to pick readlen for bracken

### ISSUE THREAD

**Issue by ramay** [jenniferlu717/Bracken#90]
Hi, 
For bracken, is the readlen parameter referring to the raw sequencing read or an average read length of trimmed reads or a minimum read length found in the dataset.  I couldn't find details on this in the manual.

Thanks!
Hena

**Comment by jenniferlu717** [comment]
It depends on the range of the read lengths. I would use the minimum read length. 

For example, when we did testing on 75bp paired reads (150bp total length when combining two pairs), we used a 75mer read length.
