### ISSUE TITLE
Can't find the taxonomy.h file

### ISSUE THREAD

**Issue by GuoHao150** [jenniferlu717/Bracken#91]
Hi,
I just git cloned the package and when I run the command `sh install_bracken.sh` it returns me `kmer2read_distr.cpp:25:22: fatal error: taxonomy.h: No such file or directory` and I can't find the `taxonomy.h` file in your repo. How am I suppose to fix this

**Comment by jenniferlu717** [comment]
I must have accidentally deleted it. I will fix that.

**Comment by jenniferlu717** [comment]
fixed it!

**Comment by GuoHao150** [comment]
Really appreciate your excellent work 谢谢
