### ISSUE TITLE
Default threshold

### ISSUE THREAD

**Issue by taltman** [jenniferlu717/Bracken#92]
Hi @jenniferlu717 . First off, thank you for creating and maintaining Bracken!

I just noticed something. The default threshold for the minimal number of reads needed to keep a species reported by Kraken(2) is specified by the "-t" argument. In the source code and in the paper, the default is specified as 10 reads. When I don't explicitly set the argument, it runs as '-t 0'. I now explicitly set it, but for other users it might be nice to make the source code, the runtime behavior, and the paper consistent. Thanks!

**Comment by jenniferlu717** [comment]
Thanks for letting me know. The change happened when I wrapped the scripts into the `bracken` and `bracken-build` shell scripts. The default for `estimate_abundance.py` is still 10, but `bracken` uses 0. I'll make the change so that the default is 10.

**Comment by jenniferlu717** [comment]
Made the change! thanks

**Comment by joshsimcock** [comment]
Hi,

Thanks for putting together and maintaining this great tool! Just a quick note that the usage message for `bracken` still states the default is 0:
`THRESHOLD      number of reads required PRIOR to abundance estimation to perform reestimation (default: 0)`
Not a biggie but useful for clarity, I didn't realise it was 10 until I saw the `stdout` without setting `-t` and then checked the script.

Thanks!
