### ISSUE TITLE
Zero division since latest commit

### ISSUE THREAD

**Issue by Wrzlprmft** [jenniferlu717/Bracken#99]
Since [the latest commit](https://github.com/jenniferlu717/Bracken/commit/18f2e03ff66e07ea3ea8e102ed0083eaaad6b860), I am getting a `ZeroDivisionError`:

```
 >> Checking for Valid Options...
 >> Running Bracken 
      >> python src/est_abundance.py -i in.dat -o out.dat -k …/database151mers.kmer_distrib -l G -t 10
PROGRAM START TIME: …
Traceback (most recent call last):
  File "…/src/est_abundance.py", line 493, in <module>
    main()
  File "…/src/est_abundance.py", line 390, in main
    o_file.write("%0.5f\n" % (float(int(new_all_reads))/float(int(sum_all_reads))))
ZeroDivisionError: float division by zero
```

This seems to be independent of the options and input file, therefore I refrain from building a minimal example for now. If you need one, please tell me.

**Comment by jenniferlu717** [comment]
I think the code has been updated since then, but I added an error message to avoid that error. 

If you continue to get that kind of error, can you send your Kraken report to jlu26@jhmi.edu.

**Comment by Wrzlprmft** [comment]
> I think the code has been updated since then

Well, it was the last in the [commit history](https://github.com/jenniferlu717/Bracken/commits/) yesterday.  But I might have erred here and the problem already emerged one commit earlier.

Anyway, it turns out the problem was that the Bracken part of the database was empty.
